package net.townymap.hunter.front;

import net.townymap.TownyMapConfig;
import net.townymap.hunter.model.*;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class HiddenThreatFrontEngineTest {
    private static HunterState hidden(String name,HunterState.Source source,long at){HunterState h=new HunterState(name,source);h.visibility=HunterState.Visibility.HIDDEN;h.online=HunterState.OnlineStatus.ONLINE;h.hiddenSinceMs=at;h.direct=new HunterState.Observation(0,0,at,HunterState.ObservationType.DIRECT_DYNMAP,"Wilderness","",HunterState.Confidence.HIGH);h.lastSeen=h.direct;return h;}
    private static ApproachRoute route(int n){return new ApproachRoute("town:"+n,"Town"+n,ApproachRoute.Type.TOWN,n*100,0,n*100,false);}
    @Test void exposureGateKeepsLastKnownActiveAndTeleportOriginsLatent(){var e=new HiddenThreatFrontEngine(new TownyMapConfig());var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);e.update(h,2_000,0,0,List.of(route(1)),null,null,null,false);assertEquals(List.of(HiddenThreatOrigin.Type.LAST_KNOWN_POSITION),e.allFronts().stream().map(f->f.origin().type()).toList());assertEquals(1,e.teleportStats("Hunter").latentOrigins());assertEquals(0,e.teleportStats("Hunter").activeLogicalOrigins());assertEquals(0,h.teleportFrontActivatedAtMs);}
    @Test void exposureActivationStartsTeleportFrontAtThresholdInsteadOfBackdating(){TownyMapConfig c=new TownyMapConfig();c.hunterFrontTeleportDelaySeconds=0;c.hunterTeleportActivationInitialRadius=64;var e=new HiddenThreatFrontEngine(c);var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);e.update(h,400_000,0,0,List.of(route(1)),null,null,null,false);e.update(h,421_000,0,0,List.of(route(1)),null,null,null,true);var teleport=e.allFronts().stream().filter(f->f.origin().type()==HiddenThreatOrigin.Type.TOWN_SPAWN).findFirst().orElseThrow();assertEquals(421_000,h.teleportFrontActivatedAtMs);assertEquals(64,teleport.plausibleRadius(),.01);assertEquals(64,teleport.warningRadius(),.01);assertTrue(e.allFronts().stream().anyMatch(f->f.origin().type()==HiddenThreatOrigin.Type.LAST_KNOWN_POSITION));}
    @Test void keepsEveryTeleportLatentButActivatesOnlySpatiallyRelevantClusters(){TownyMapConfig c=new TownyMapConfig();c.hunterTeleportThreatClusterRadius=32;var e=new HiddenThreatFrontEngine(c);var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);e.update(h,2_000,0,0,List.of(route(1),route(2)));assertEquals(2,e.teleportStats("Hunter").latentOrigins());assertEquals(3,e.allFronts().size());}
    @Test void warningFrontExpandsFasterThanPlausible(){var e=new HiddenThreatFrontEngine(new TownyMapConfig());e.update(hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000),11_000,10_000,10_000,List.of());var f=e.allFronts().getFirst();assertTrue(f.warningRadius()>f.plausibleRadius());}
    @Test void expandingFrontCrossesStationaryPlayerExactlyOnce(){TownyMapConfig c=new TownyMapConfig();c.hunterFrontWarningLeadSeconds=0;var e=new HiddenThreatFrontEngine(c);var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);assertTrue(e.update(h,2_000,100,0,List.of()).crossings().isEmpty());assertEquals(1,e.update(h,7_000,100,0,List.of()).crossings().stream().filter(x->x.type()==HiddenThreatFrontEngine.FrontType.WARNING).count());assertTrue(e.update(h,8_000,100,0,List.of()).crossings().isEmpty());}
    @Test void playerMovementIntoExistingFrontCountsAsCrossing(){TownyMapConfig c=new TownyMapConfig();c.hunterFrontWarningLeadSeconds=0;var e=new HiddenThreatFrontEngine(c);var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);e.update(h,11_000,200,0,List.of());assertFalse(e.update(h,11_000,100,0,List.of()).crossings().isEmpty());}
    @Test void hysteresisPreventsBoundarySpam(){TownyMapConfig c=new TownyMapConfig();c.hunterFrontWarningLeadSeconds=0;c.hunterFrontReentryHysteresis=32;var e=new HiddenThreatFrontEngine(c);var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);e.update(h,11_000,100,0,List.of());e.update(h,11_000,125,0,List.of());assertTrue(e.update(h,11_000,100,0,List.of()).crossings().isEmpty());}
    @Test void plausibleFrontLaterCrossesPlayer(){TownyMapConfig c=new TownyMapConfig();c.hunterFrontWarningLeadSeconds=0;var e=new HiddenThreatFrontEngine(c);var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);e.update(h,2_000,100,0,List.of());assertEquals(1,e.update(h,14_000,100,0,List.of()).crossings().stream().filter(x->x.type()==HiddenThreatFrontEngine.FrontType.PLAUSIBLE).count());}
    @Test void potentialHunterUsesSameGeometry(){var e=new HiddenThreatFrontEngine(new TownyMapConfig());e.update(hidden("Candidate",HunterState.Source.AUTO_HIGH_OUTLAW,1_000),11_000,10_000,0,List.of());var f=e.allFronts().getFirst();assertEquals(112,f.plausibleRadius(),.01);assertEquals(272,f.warningRadius(),.01);}
    @Test void renderLimitNeverLimitsRelevantLogicalEvaluation(){TownyMapConfig c=new TownyMapConfig();c.hunterFrontWarningLeadSeconds=0;c.hunterTeleportThreatClusterRadius=32;c.hunterMaxRelevantTeleportThreats=60;var e=new HiddenThreatFrontEngine(c);var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);var routes=new ArrayList<ApproachRoute>();for(int i=1;i<=60;i++)routes.add(route(i));e.update(h,20_000,3700,0,routes);assertEquals(60,e.teleportStats("Hunter").latentOrigins());assertTrue(e.allFronts().size()>5);assertEquals(5,e.renderFronts(5).size());assertTrue(e.allFronts().stream().anyMatch(HiddenThreatFrontEngine.Front::playerInsideWarning));}
    @Test void renderingLimitReservesSpaceForTeleportOrigins(){var e=new HiddenThreatFrontEngine(new TownyMapConfig());for(int i=0;i<12;i++)e.update(hidden("Hunter"+i,HunterState.Source.MANUAL_HUNTER,1_000),2_000,0,0,List.of(route(i+1)));var rendered=e.renderFronts(8);assertTrue(rendered.stream().anyMatch(f->f.origin().type()==HiddenThreatOrigin.Type.TOWN_SPAWN),rendered.toString());assertTrue(rendered.stream().anyMatch(f->f.origin().type()==HiddenThreatOrigin.Type.LAST_KNOWN_POSITION),rendered.toString());}
    @Test void perHunterAndGlobalRenderCapsApplyAcrossHunters(){TownyMapConfig c=new TownyMapConfig();c.hunterTeleportThreatClusterRadius=32;var e=new HiddenThreatFrontEngine(c);for(int h=0;h<3;h++){var routes=new ArrayList<ApproachRoute>();for(int i=0;i<10;i++)routes.add(new ApproachRoute("town:"+h+":"+i,"T"+h+"-"+i,ApproachRoute.Type.TOWN,i*400,0,i*400,false));e.update(hidden("H"+h,HunterState.Source.MANUAL_HUNTER,1_000),2_000,0,0,routes);}var rendered=e.renderFronts(7,2);assertTrue(rendered.size()<=7);var counts=rendered.stream().filter(f->f.origin().type()==HiddenThreatOrigin.Type.TOWN_SPAWN).collect(java.util.stream.Collectors.groupingBy(f->f.origin().hunterKey(),java.util.stream.Collectors.counting()));assertTrue(counts.values().stream().allMatch(n->n<=2));}
    @Test void aggregateWarningFiresOncePerHunterSeverity(){TownyMapConfig c=new TownyMapConfig();c.hunterFrontWarningLeadSeconds=0;c.hunterTeleportActivationInitialRadius=0;c.hunterTeleportThreatClusterRadius=32;var e=new HiddenThreatFrontEngine(c);var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);h.direct=new HunterState.Observation(10_000,0,1_000,HunterState.ObservationType.DIRECT_DYNMAP,"Wilderness","",HunterState.Confidence.HIGH);h.lastSeen=h.direct;var routes=List.of(new ApproachRoute("town:a","A",ApproachRoute.Type.TOWN,100,0,100,false),new ApproachRoute("town:b","B",ApproachRoute.Type.TOWN,-100,0,100,false));var initial=e.update(h,2_000,0,0,routes);assertTrue(initial.crossings().isEmpty(),initial.toString());var warning=e.update(h,18_000,0,0,routes);assertEquals(1,warning.crossings().stream().filter(x->x.type()==HiddenThreatFrontEngine.FrontType.WARNING).count(),warning.toString());var repeated=e.update(h,19_000,0,0,routes);assertTrue(repeated.crossings().isEmpty(),repeated.toString());var plausible=e.update(h,23_000,0,0,routes);assertEquals(1,plausible.crossings().stream().filter(x->x.type()==HiddenThreatFrontEngine.FrontType.PLAUSIBLE).count(),plausible.toString());}
    @Test void reappearanceImmediatelyDeletesLastKnownTownAndNationFronts(){TownyMapConfig c=new TownyMapConfig();c.hunterTeleportThreatClusterRadius=32;var e=new HiddenThreatFrontEngine(c);var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);var nation=new ApproachRoute("nation:a","NationA",ApproachRoute.Type.NATION,400,0,400,false);e.update(h,2_000,0,0,List.of(route(1),nation));assertEquals(Set.of(HiddenThreatOrigin.Type.LAST_KNOWN_POSITION,HiddenThreatOrigin.Type.TOWN_SPAWN,HiddenThreatOrigin.Type.NATION_SPAWN),e.allFronts().stream().map(f->f.origin().type()).collect(java.util.stream.Collectors.toSet()));h.visibility=HunterState.Visibility.VISIBLE;e.update(h,2_001,0,0,List.of());assertTrue(e.allFronts().isEmpty());}
    @Test void combatAnchorIsHighPriorityAndSmallInitially(){var e=new HiddenThreatFrontEngine(new TownyMapConfig());var h=hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000);h.inferred=new HunterState.Observation(50,50,1_500,HunterState.ObservationType.COMBAT_INFERRED,"Wilderness","",HunterState.Confidence.HIGH);e.update(h,2_000,1000,1000,List.of());var kill=e.allFronts().stream().filter(f->f.origin().type()==HiddenThreatOrigin.Type.KILL_EVENT_ORIGIN).findFirst().orElseThrow();assertTrue(kill.plausibleRadius()<e.allFronts().stream().filter(f->f.origin().type()==HiddenThreatOrigin.Type.LAST_KNOWN_POSITION).findFirst().orElseThrow().plausibleRadius());assertTrue(kill.relevance()>0);}
    @Test void manyOriginsStayLatentAndUpdateWithinBudget(){var e=new HiddenThreatFrontEngine(new TownyMapConfig());var routes=new ArrayList<ApproachRoute>();for(int i=0;i<1000;i++)routes.add(route(i));long start=System.nanoTime();e.update(hidden("Hunter",HunterState.Source.MANUAL_HUNTER,1_000),20_000,0,0,routes);assertTrue((System.nanoTime()-start)/1_000_000<500);assertEquals(1000,e.teleportStats("Hunter").latentOrigins());assertTrue(e.allFronts().size()<=26);}
}
