package net.townymap.hunter;

import net.townymap.hunter.tracking.WildernessExposureSession;
import net.townymap.model.TownData;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class WildernessExposureSessionTest {
    private static TownData town(String name,int x,int z){return new TownData(name,0,Collections.singletonList(new int[][]{{x-8,z-8},{x+8,z-8},{x+8,z+8},{x-8,z+8}}));}
    private static WildernessExposureSession session(){return new WildernessExposureSession(3000,24,30_000,60_000,300_000);}
    @Test void briefWildernessTouchCancelsWithoutSession(){var s=session();s.update(true,0,0,List.of(),1_000);assertEquals(WildernessExposureSession.State.ENTRY_BUFFER,s.state());s.update(false,0,0,List.of(),11_000);assertEquals(WildernessExposureSession.State.SAFE,s.state());assertEquals(0,s.cumulativeExposureMs(11_000));assertEquals(0,s.sessionId());}
    @Test void allAllowedTransitionsPreserveOrEndTheSession(){var s=session();s.update(true,0,0,List.of(),1_000);assertEquals(WildernessExposureSession.Transition.BUFFER_STARTED,s.transition());s.update(true,0,0,List.of(),31_000);assertEquals(WildernessExposureSession.State.ACTIVE,s.state());assertEquals(WildernessExposureSession.Transition.SESSION_STARTED,s.transition());long id=s.sessionId();s.update(false,0,0,List.of(),211_000);assertEquals(WildernessExposureSession.State.CLAIM_GRACE,s.state());assertEquals(180_000,s.cumulativeExposureMs(230_000));s.update(true,0,0,List.of(),231_000);assertEquals(WildernessExposureSession.State.ACTIVE,s.state());assertEquals(id,s.sessionId());assertEquals(180_000,s.cumulativeExposureMs(231_000));s.update(false,0,0,List.of(),251_000);s.update(false,0,0,List.of(),311_001);assertEquals(WildernessExposureSession.State.SAFE,s.state());assertEquals(WildernessExposureSession.Transition.SESSION_ENDED,s.transition());assertEquals(0,s.cumulativeExposureMs(311_001));s.update(true,0,0,List.of(),320_000);assertEquals(WildernessExposureSession.State.ENTRY_BUFFER,s.state());s.update(true,0,0,List.of(),350_000);assertTrue(s.sessionId()>id);}
    @Test void cumulativeCountsOnlyActiveSegments(){var s=session();s.update(true,0,0,List.of(),0);s.update(true,0,0,List.of(),30_000);s.update(true,0,0,List.of(),150_000);assertEquals(120_000,s.cumulativeExposureMs(150_000));s.update(false,0,0,List.of(),150_000);assertEquals(120_000,s.cumulativeExposureMs(190_000));s.update(true,0,0,List.of(),190_000);assertEquals(150_000,s.cumulativeExposureMs(220_000));}
    @Test void modifierUsesConfigurableTargetAndCaps(){assertEquals(0,WildernessExposureSession.modifier(0,300_000));assertTrue(WildernessExposureSession.modifier(180_000,300_000)>0);assertEquals(.5,WildernessExposureSession.modifier(300_000,300_000),.001);assertEquals(1,WildernessExposureSession.modifier(500_000,300_000),.001);}
    @Test void indexesOnlyAfterActivationAndOnMeaningfulMovement(){var s=session();var towns=List.of(town("Near",100,0),town("Far",4000,0));s.update(true,0,0,towns,1_000);assertTrue(s.entries().isEmpty());s.update(true,0,0,towns,31_000);assertEquals(List.of("Near"),s.entries().stream().map(WildernessExposureSession.Entry::name).toList());long revision=s.revision();assertFalse(s.update(true,10,0,towns,31_100));assertTrue(s.update(true,40,0,towns,31_200));assertTrue(s.revision()>revision);}
    @Test void recordsRecentTownAndNationEntriesWithinSession(){var s=session();s.update(true,0,0,List.of(),0);s.update(true,0,0,List.of(),30_000);s.recordCommand("/t spawn Alpha",31_000);assertTrue(s.recentEntry(32_000).matches("Alpha"));s.recordCommand("n spawn Beta",33_000);assertEquals(WildernessExposureSession.Entry.Type.NATION,s.recentEntry(34_000).type());}
    @Test void resetClearsLifecycleState(){var s=session();s.update(true,0,0,List.of(),0);s.update(true,0,0,List.of(),30_000);s.reset();assertEquals(WildernessExposureSession.State.SAFE,s.state());assertEquals(0,s.cumulativeExposureMs(100_000));assertTrue(s.entries().isEmpty());}
}
