package net.townymap.gui;

import net.minecraft.client.gui.GuiGraphicsExtractor;import net.minecraft.client.gui.components.*;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.*;import net.townymap.*;import net.townymap.hunter.config.HunterWatchlist;import net.townymap.hunter.discovery.HunterCandidateService;import java.util.*;
public final class HunterCandidateScreen extends Screen{
 private static final int ROW=28;private final Screen parent;private TownyMapConfig cfg;private EditBox search,check;private int left,right,top,bottom,scroll;private Component lookup=Component.empty();
 public HunterCandidateScreen(Screen p){super(Component.translatable("townymapaddon.hunter.candidates.title"));parent=p;}@Override protected void init(){cfg=TownyMapMod.getConfig();left=Math.max(8,(width-Math.min(600,width-16))/2);right=width-left;top=98;bottom=Math.max(top+40,height-42);search=new EditBox(font,left+10,42,170,20,Component.translatable("townymapaddon.common.filter"));search.setHint(Component.translatable("townymapaddon.hunter.candidates.filter_hint"));search.setResponder(v->{scroll=0;rebuildWidgets();});addRenderableWidget(search);check=new EditBox(font,left+190,42,150,20,Component.translatable("townymapaddon.common.player"));check.setHint(Component.translatable("townymapaddon.hunter.candidates.check_hint"));addRenderableWidget(check);addRenderableWidget(Button.builder(Component.translatable("townymapaddon.common.check"),b->lookup()).bounds(left+344,42,52,20).build());var svc=TownyMapMod.hunterCandidateService();addRenderableWidget(Button.builder(Component.translatable(svc!=null&&svc.refreshing()?"townymapaddon.common.refreshing":"townymapaddon.hunter.candidates.refresh"),b->{if(svc!=null)svc.refresh(TownyMapMod.currentTownSnapshot());}).bounds(right-142,42,132,20).build());List<HunterCandidateService.Candidate>list=svc==null?List.of():svc.candidates(search.getValue());scroll=Math.clamp(scroll,0,Math.max(0,list.size()*ROW-(bottom-top)));for(int i=0;i<list.size();i++){var candidate=list.get(i);int y=top+i*ROW-scroll;if(y<top||y+ROW>bottom)continue;boolean watched=cfg.hunterWatchlist.stream().anyMatch(n->n.equalsIgnoreCase(candidate.name()));addRenderableWidget(Button.builder(Component.translatable(watched?"townymapaddon.hunter.candidates.watched":"townymapaddon.hunter.candidates.add"),b->{if(!watched){HunterWatchlist.add(cfg,candidate.name());rebuildWidgets();}}).bounds(right-102,y+4,92,20).build());}addRenderableWidget(Button.builder(CommonComponents.GUI_DONE,b->onClose()).bounds(right-90,height-30,80,20).build());}
 private void lookup(){var svc=TownyMapMod.hunterCandidateService();if(svc!=null){var c=svc.lookup(check.getValue());lookup=Component.translatable("townymapaddon.hunter.candidates.lookup",c.name(),c.outlawTownCount());}}
 @Override public boolean mouseScrolled(double x,double y,double h,double v){var svc=TownyMapMod.hunterCandidateService();int n=svc==null?0:svc.candidates(search.getValue()).size();scroll=Math.clamp(scroll-(int)Math.round(v*ROW),0,Math.max(0,n*ROW-(bottom-top)));rebuildWidgets();return true;}
 @Override public void extractRenderState(GuiGraphicsExtractor c,int mx,int my,float d){c.fill(left-2,18,right+2,height-8,0xCC080A0D);c.fill(left,20,right,height-10,0xEE15181C);c.fill(left,20,right,23,0xFF4FA37A);super.extractRenderState(c,mx,my,d);c.centeredText(font,title,width/2,25,0xFFFFFFFF);c.text(font,Component.translatable("townymapaddon.hunter.candidates.heuristic",cfg.hunterCandidateOutlawThreshold),left+10,68,0xFFB9BFC7,false);var svc=TownyMapMod.hunterCandidateService();if(svc==null)return;long age=svc.refreshedAtMs()==0?0:System.currentTimeMillis()-svc.refreshedAtMs();Component meta=Component.translatable(svc.failed()?"townymapaddon.hunter.candidates.meta_failed":svc.refreshing()?"townymapaddon.hunter.candidates.meta_refreshing":"townymapaddon.hunter.candidates.meta",svc.townsScanned(),age(age));c.text(font,meta,left+10,82,svc.failed()?0xFFFFAA55:0xFF858B93,false);if(!lookup.getString().isBlank())c.text(font,lookup,left+405,48,0xFF9ED8B5,false);List<HunterCandidateService.Candidate>list=svc.candidates(search.getValue());for(int i=0;i<list.size();i++){var q=list.get(i);int y=top+i*ROW-scroll;if(y<top||y+ROW>bottom)continue;c.text(font,q.name(),left+14,y+9,0xFFFFFFFF,false);c.text(font,Component.translatable("townymapaddon.hunter.candidates.outlawed",q.outlawTownCount()),left+180,y+9,0xFFFFB45C,false);}}
 private static Component age(long ms){if(ms<=0)return Component.translatable("townymapaddon.common.never");long s=ms/1000;return Component.translatable(s<60?"townymapaddon.common.seconds_short":"townymapaddon.common.minutes_short",s<60?s:s/60);}@Override public void onClose(){minecraft.gui.setScreen(parent);}
}
