package net.townymap.gui;

import net.minecraft.client.gui.DrawContext;import net.minecraft.client.gui.screen.Screen;import net.minecraft.client.gui.widget.*;import net.minecraft.screen.ScreenTexts;import net.minecraft.text.Text;import net.townymap.*;import net.townymap.hunter.config.HunterWatchlist;import net.townymap.hunter.discovery.HunterCandidateService;import java.util.*;
public final class HunterCandidateScreen extends Screen{
 private static final int ROW=28;private final Screen parent;private TownyMapConfig cfg;private TextFieldWidget search,check;private int left,right,top,bottom,scroll;private String lookup="";
 public HunterCandidateScreen(Screen p){super(Text.literal("Hunter Candidates"));parent=p;}@Override protected void init(){cfg=TownyMapMod.getConfig();left=Math.max(8,(width-Math.min(600,width-16))/2);right=width-left;top=98;bottom=Math.max(top+40,height-42);search=new TextFieldWidget(textRenderer,left+10,42,170,20,Text.literal("Filter"));search.setPlaceholder(Text.literal("Filter candidates"));search.setChangedListener(v->{scroll=0;clearAndInit();});addDrawableChild(search);check=new TextFieldWidget(textRenderer,left+190,42,150,20,Text.literal("Player"));check.setPlaceholder(Text.literal("Check player"));addDrawableChild(check);addDrawableChild(ButtonWidget.builder(Text.literal("Check"),b->lookup()).dimensions(left+344,42,52,20).build());var svc=TownyMapMod.hunterCandidateService();addDrawableChild(ButtonWidget.builder(Text.literal(svc!=null&&svc.refreshing()?"Refreshing…":"Refresh Candidates"),b->{if(svc!=null)svc.refresh(TownyMapMod.currentTownSnapshot());}).dimensions(right-142,42,132,20).build());List<HunterCandidateService.Candidate>list=svc==null?List.of():svc.candidates(search.getText());scroll=Math.clamp(scroll,0,Math.max(0,list.size()*ROW-(bottom-top)));for(int i=0;i<list.size();i++){var candidate=list.get(i);int y=top+i*ROW-scroll;if(y<top||y+ROW>bottom)continue;boolean watched=cfg.hunterWatchlist.stream().anyMatch(n->n.equalsIgnoreCase(candidate.name()));addDrawableChild(ButtonWidget.builder(Text.literal(watched?"WATCHED":"Add Hunter"),b->{if(!watched){HunterWatchlist.add(cfg,candidate.name());clearAndInit();}}).dimensions(right-92,y+4,82,20).build());}addDrawableChild(ButtonWidget.builder(ScreenTexts.DONE,b->close()).dimensions(right-90,height-30,80,20).build());}
 private void lookup(){var svc=TownyMapMod.hunterCandidateService();if(svc!=null){var c=svc.lookup(check.getText());lookup=c.name()+": outlawed by "+c.outlawTownCount()+" unique towns";}}@Override public boolean mouseScrolled(double x,double y,double h,double v){var svc=TownyMapMod.hunterCandidateService();int n=svc==null?0:svc.candidates(search.getText()).size();scroll=Math.clamp(scroll-(int)Math.round(v*ROW),0,Math.max(0,n*ROW-(bottom-top)));clearAndInit();return true;}
 @Override public void render(DrawContext c,int mx,int my,float d){c.fill(left-2,18,right+2,height-8,0xCC080A0D);c.fill(left,20,right,height-10,0xEE15181C);c.fill(left,20,right,23,0xFF4FA37A);super.render(c,mx,my,d);c.drawCenteredTextWithShadow(textRenderer,title,width/2,25,0xFFFFFFFF);c.drawText(textRenderer,"Outlawed by more than "+cfg.hunterCandidateOutlawThreshold+" towns. Heuristic only; not proof.",left+10,68,0xFFB9BFC7,false);var svc=TownyMapMod.hunterCandidateService();if(svc==null)return;long age=svc.refreshedAtMs()==0?0:System.currentTimeMillis()-svc.refreshedAtMs();String meta=(svc.failed()?"Update failed · cached · ":svc.refreshing()?"Refreshing · ":"")+"Scanned "+svc.townsScanned()+" towns · Updated "+age(age)+" ago";c.drawText(textRenderer,meta,left+10,82,svc.failed()?0xFFFFAA55:0xFF858B93,false);if(!lookup.isBlank())c.drawText(textRenderer,lookup,left+405,48,0xFF9ED8B5,false);List<HunterCandidateService.Candidate>list=svc.candidates(search.getText());for(int i=0;i<list.size();i++){var q=list.get(i);int y=top+i*ROW-scroll;if(y<top||y+ROW>bottom)continue;c.drawText(textRenderer,q.name(),left+14,y+9,0xFFFFFFFF,false);c.drawText(textRenderer,"Outlawed by "+q.outlawTownCount()+" towns",left+180,y+9,0xFFFFB45C,false);}}private static String age(long ms){if(ms<=0)return"never";long s=ms/1000;return s<60?s+"s":s/60+"m";}@Override public void close(){client.setScreen(parent);}
}
