package net.townymap.gui;

import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.CommonComponents;
import net.minecraft.network.chat.Component;
import net.townymap.TownyMapConfig;
import net.townymap.TownyMapMod;
import net.townymap.hunter.config.HunterWatchlist;

/** Responsive, scrollable watchlist editor shared by Mod Menu and Xaero. */
public final class HunterWatchScreen extends Screen {
    private static final int ROW=26, SETTINGS=9; private final Screen parent; private TownyMapConfig cfg;
    private EditBox input; private int left,right,top,bottom,scroll; private String feedback="";
    public HunterWatchScreen(Screen parent){super(Component.translatable("townymapaddon.hunter.watch.title"));this.parent=parent;}
    @Override protected void init(){cfg=TownyMapMod.getConfig();left=Math.max(10,(width-Math.min(560,width-20))/2);right=width-left;top=82;bottom=Math.max(top+40,height-42);int total=cfg.hunterWatchlist.size()*ROW+8+SETTINGS*ROW;scroll=Math.clamp(scroll,0,Math.max(0,total-(bottom-top)));input=new EditBox(font,left+12,42,Math.max(80,right-left-112),20,Component.literal("Hunter names"));input.setMaxLength(512);input.setHint(Component.literal("HunterA, HunterB, HunterC"));addRenderableWidget(input);addRenderableWidget(Button.builder(Component.literal("Add Hunters"),b->add()).bounds(right-94,42,82,20).build());int cy=0;for(String name:cfg.hunterWatchlist){int y=top+cy-scroll;if(visible(y)){boolean enabled=HunterWatchlist.enabled(cfg,name);addRenderableWidget(Button.builder(Component.literal(enabled?"Enabled":"Disabled"),b->{HunterWatchlist.setEnabled(cfg,name,!enabled);rebuildWidgets();}).bounds(right-154,y+3,72,20).build());addRenderableWidget(Button.builder(Component.literal("Remove"),b->{HunterWatchlist.remove(cfg,name);rebuildWidgets();}).bounds(right-76,y+3,64,20).build());}cy+=ROW;}cy+=8;cy=toggle(cy,"Hunter System",cfg.hunterWarningEnabled,()->cfg.hunterWarningEnabled=!cfg.hunterWarningEnabled);cy=toggle(cy,"Show Hunter HUD",cfg.hunterShowHud,()->cfg.hunterShowHud=!cfg.hunterShowHud);cy=toggle(cy,"Show Activity Window",cfg.hunterActivityWindowShown,()->cfg.hunterActivityWindowShown=!cfg.hunterActivityWindowShown);cy=toggle(cy,"Notifications In Chat",cfg.hunterNotificationsInChat,()->cfg.hunterNotificationsInChat=!cfg.hunterNotificationsInChat);cy=toggle(cy,"Warnings In Chat",cfg.hunterWarningsInChat,()->cfg.hunterWarningsInChat=!cfg.hunterWarningsInChat);cy=toggle(cy,"Show Direction",cfg.hunterDirectionEnabled,()->cfg.hunterDirectionEnabled=!cfg.hunterDirectionEnabled);cy=range(cy,"Nearby HUD Range",true);cy=range(cy,"Teleport Threat Range",false);int y=top+cy-scroll;if(visible(y))addRenderableWidget(Button.builder(Component.literal("Open Hunter Candidates"),b->minecraft.gui.setScreen(new HunterCandidateScreen(this))).bounds(left+16,y+3,170,20).build());addRenderableWidget(Button.builder(CommonComponents.GUI_DONE,b->onClose()).bounds(right-92,height-30,80,20).build());}
    private int toggle(int cy,String label,boolean value,Runnable action){int y=top+cy-scroll;if(visible(y))addRenderableWidget(Button.builder(Component.literal(value?"ON":"OFF"),b->{action.run();cfg.save();rebuildWidgets();}).bounds(right-76,y+3,64,20).build());return cy+ROW;}
    private int range(int cy,String label,boolean near){int y=top+cy-scroll;int value=near?cfg.hunterNearbyRadius:cfg.hunterTeleportThreatRadius;if(visible(y))addRenderableWidget(Button.builder(Component.literal(value+" blocks"),b->{int[]v=near?new int[]{500,1000,2000,5000}:new int[]{1000,2000,3000,5000};int n=v[0];for(int i=0;i<v.length;i++)if(v[i]==value)n=v[(i+1)%v.length];if(near)cfg.hunterNearbyRadius=n;else cfg.hunterTeleportThreatRadius=n;cfg.save();rebuildWidgets();}).bounds(right-116,y+3,104,20).build());return cy+ROW;}
    private boolean visible(int y){return y>=top&&y+ROW<=bottom;}private void add(){var r=HunterWatchlist.add(cfg,input.getValue());feedback=r.added()+" added"+(r.rejected()>0?", "+r.rejected()+" invalid":"");input.setValue("");rebuildWidgets();}
    @Override public boolean mouseScrolled(double x,double y,double h,double v){int total=cfg.hunterWatchlist.size()*ROW+8+SETTINGS*ROW;scroll=Math.clamp(scroll-(int)Math.round(v*ROW),0,Math.max(0,total-(bottom-top)));rebuildWidgets();return true;}
    @Override public void extractRenderState(GuiGraphicsExtractor c,int mx,int my,float d){c.fill(left-2,18,right+2,height-8,0xCC080A0D);c.fill(left,20,right,height-10,0xEE15181C);c.fill(left,20,right,23,0xFF4FA37A);super.extractRenderState(c,mx,my,d);c.centeredText(font,title,width/2,25,0xFFFFFFFF);c.text(font,"Watched Hunters",left+12,68,0xFFE4E7EB,false);if(!feedback.isBlank())c.text(font,feedback,right-font.width(feedback)-12,68,0xFF9ED8B5,false);int cy=0;for(String name:cfg.hunterWatchlist){int y=top+cy-scroll;if(visible(y))c.text(font,name,left+16,y+9,HunterWatchlist.enabled(cfg,name)?0xFFFFFFFF:0xFF858B93,false);cy+=ROW;}cy+=8;String[]labels={"Hunter System","Show Hunter HUD","Show Activity Window","Notifications In Chat","Warnings In Chat","Show Direction","Nearby HUD Range","Teleport Threat Range"};for(String label:labels){int y=top+cy-scroll;if(visible(y))c.text(font,label,left+16,y+9,0xFFD8DDE3,false);cy+=ROW;}}
    @Override public void onClose(){minecraft.gui.setScreen(parent);}
}
