package net.townymap.gui;

import com.google.gson.*;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.townymap.TownyMapMod;
import org.lwjgl.glfw.GLFW;

import java.io.IOException;
import java.nio.file.*;
import java.util.*;

/** In-map editor and website-compatible highways.json exporter. */
public final class IceRoadPlannerOverlay {
    private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create();
    private static final String[] TYPES={"line","station","semi1","semi2","semi3","semi4","jct","inter1","inter2","elev-ew","elev-we"};
    private static final String[] LABELS={"Line","Station","Semi N","Semi E","Semi S","Semi W","Junction","Interchange A","Interchange B","Elevator E-W","Elevator W-E"};
    private static final String[] COORDINATE_MODES={"All","Turns + Y changes","Markers","Hidden","Graphic only"};
    private static final int[] LABEL_VERTICAL_OFFSETS={-5,9,-19,23,-33,37,-47};
    private static final int W=230,ROW=20,MAX_BRANCH_ROWS=4;
    private static boolean active,loaded,toolDropdown,draftDropdown,dragging,dragArmed,pendingPlacement,dragUndoRecorded,markerEditing,segmentEditing,pointEditing,pointConnecting,branchPanel,newLinePending,pendingImageExport;private static int tool,draftIndex,coordinateField,nameEditing,selectedMarker=-1,selectedPointBranch=-1,selectedPoint=-1,selectedSegmentBranch=-1,selectedSegment=-1,dragStation=-1,dragBranch=-1,dragVertex=-1;private static double gestureStartX,gestureStartY,pendingWorldX,pendingWorldZ;private static String coordinateX="",coordinateY="64",coordinateZ="",nameInput="",feedback="";private static long feedbackUntil,imageExportStartedAt;
    private static final List<Draft> drafts=new ArrayList<>();
    private static final Deque<JsonObject> undoHistory=new ArrayDeque<>();
    private static final Deque<JsonObject> redoHistory=new ArrayDeque<>();
    private static Point selectedSegmentPoint;
    private static Point connectionStart;
    private static List<DragHit> dragHits=List.of();
    private static List<SegmentHit> segmentHits=List.of();
    private record Point(double x,double z){} private record Link(Point a,Point b){} private record Station(int id,String name,String type,double x,double y,double z){}
    private record DragHit(int station,int branch,int vertex,double x,double y){}
    private record SegmentHit(int branch,int segment,double ax,double ay,double bx,double by){}
    private static final class Branch {String name;double y=64;final List<Point>vertices=new ArrayList<>();final NavigableSet<Integer>breaks=new TreeSet<>();final List<Link>links=new ArrayList<>();final List<Integer>stationIds=new ArrayList<>();Branch(String n){name=n;}}
    private static final class Draft {String name,company="My Highway",line="Planned Line",prefix="",code="",color="ff55dd";boolean showMarkerInfo=true;int coordinateMode;final List<Station>stations=new ArrayList<>();final List<Branch>branches=new ArrayList<>();int branch;Draft(String n){name=n;branches.add(new Branch("Main"));}}
    private IceRoadPlannerOverlay(){}
    public static boolean active(){return active;}public static void toggle(){ensureLoaded();active=!active;if(!active)clearMarkerSelection();}
    private static void ensureLoaded(){if(loaded)return;loaded=true;loadLibrary();if(drafts.isEmpty())drafts.add(new Draft("Draft 1"));}
    private static Draft draft(){ensureLoaded();draftIndex=Math.clamp(draftIndex,0,drafts.size()-1);return drafts.get(draftIndex);}
    private static Branch branch(){Draft d=draft();d.branch=Math.clamp(d.branch,0,d.branches.size()-1);return d.branches.get(d.branch);}

    public static void render(GuiGraphicsExtractor g,double camX,double camZ,double scale,int sw,int sh){if(!active||scale<=0)return;boolean export=TownyMapMod.composingPlannerExport();if(!export)updateDragGesture();if(dragging&&!export)updateDrag(camX,camZ,scale,sw,sh);Draft d=draft();List<DragHit> hits=new ArrayList<>();List<SegmentHit> segments=new ArrayList<>();for(int bi=0;bi<d.branches.size();bi++){Branch b=d.branches.get(bi);int color=bi==d.branch?0xFFFF55DD:0xAA7E8E99;for(int i=1;i<b.vertices.size();i++){if(b.breaks.contains(i))continue;Point a=b.vertices.get(i-1),c=b.vertices.get(i);int ax=sx(a.x,camX,scale,sw),ay=sy(a.z,camZ,scale,sh),cx=sx(c.x,camX,scale,sw),cy=sy(c.z,camZ,scale,sh);segments.add(new SegmentHit(bi,i-1,ax,ay,cx,cy));boolean selected=!export&&bi==selectedSegmentBranch&&i-1==selectedSegment;line(g,ax,ay,cx,cy,selected?0xFFFFFF55:color,selected?4:bi==d.branch?2:1);}for(int i=0;i<b.vertices.size();i++){Point p=b.vertices.get(i);hits.add(new DragHit(-1,bi,i,sx(p.x,camX,scale,sw),sy(p.z,camZ,scale,sh)));}}drawPointLinks(g,d,camX,camZ,scale,sw,sh);drawPlannerPoints(g,hits,sw,sh,d.coordinateMode==1?topologyCoordinateKeys(d):Set.of());if(!export&&d.coordinateMode!=4)drawRouteNames(g,d,camX,camZ,scale,sw,sh);List<int[]>stationOccupied=new ArrayList<>();for(Station s:d.stations){int x=sx(s.x,camX,scale,sw),y=sy(s.z,camZ,scale,sh);hits.add(new DragHit(s.id,-1,-1,x,y));IceRoadOverlay.drawStationSymbol(g,x,y,s.type,14);if(d.coordinateMode!=4)placePointLabel(g,x,y,stationLabel(d,s,export),s.id==selectedMarker?0xFFFFD36A:0xFFFFFFFF,stationOccupied,sw,sh);}dragHits=List.copyOf(hits);segmentHits=List.copyOf(segments);if(!TownyMapMod.composingScreenshot()){panel(g,sw);actionOverlay(g,sw);markerPanel(g,sw);segmentPanel(g,sw);pointPanel(g,sw);branchPanel(g,sw);namePanel(g,sw);}}
    private static void label(GuiGraphicsExtractor g,int x,int y,String text,int color){g.fill(x+8,y-5,x+12+Minecraft.getInstance().font.width(text),y+7,0xCC071014);g.text(Minecraft.getInstance().font,text,x+10,y-3,color,false);}
    private static void drawRouteNames(GuiGraphicsExtractor g,Draft d,double camX,double camZ,double scale,int sw,int sh){for(Branch b:d.branches)if(b.vertices.size()>=2){Point a=b.vertices.getFirst(),c=b.vertices.get(1);double x=(a.x+c.x)/2,z=(a.z+c.z)/2;label(g,sx(x,camX,scale,sw),sy(z,camZ,scale,sh),d.line+" · "+b.name,0xFF8FD9FF);}}
    private static void drawPointLinks(GuiGraphicsExtractor g,Draft d,double camX,double camZ,double scale,int sw,int sh){for(int bi=0;bi<d.branches.size();bi++){Branch b=d.branches.get(bi);int color=bi==d.branch?0xFFFF55DD:0xAA7E8E99;for(Link link:b.links)line(g,sx(link.a.x,camX,scale,sw),sy(link.a.z,camZ,scale,sh),sx(link.b.x,camX,scale,sw),sy(link.b.z,camZ,scale,sh),color,bi==d.branch?2:1);}}
    private static DragHit nearestHit(double x,double y){if(newLinePending)return null;DragHit best=null;double distance=100;for(DragHit hit:dragHits){if(pointConnecting&&hit.station>=0)continue;double q=(hit.x-x)*(hit.x-x)+(hit.y-y)*(hit.y-y)-(hit.station<0?25:0);if(q<=distance){distance=q;best=hit;}}return best;}
    static boolean shouldDragPoint(boolean editingPoint,int selectedBranch,int selectedVertex,boolean editingSegment,int segmentBranch,int segmentVertex,int hitBranch,int hitVertex){return editingPoint&&hitBranch==selectedBranch&&hitVertex==selectedVertex||editingSegment&&hitBranch==segmentBranch&&(hitVertex==segmentVertex||hitVertex==segmentVertex+1);}
    private static SegmentHit nearestSegment(double x,double y){if(newLinePending||pointConnecting)return null;SegmentHit best=null;double distance=36;for(SegmentHit hit:segmentHits){double q=screenSegmentDistance2(x,y,hit.ax,hit.ay,hit.bx,hit.by);if(q<=distance){distance=q;best=hit;}}return best;}private static double screenSegmentDistance2(double x,double y,double ax,double ay,double bx,double by){double dx=bx-ax,dy=by-ay,q=dx*dx+dy*dy,t=q==0?0:Math.clamp(((x-ax)*dx+(y-ay)*dy)/q,0,1),px=ax+t*dx,py=ay+t*dy;return (x-px)*(x-px)+(y-py)*(y-py);}
    private static void updateDrag(double camX,double camZ,double scale,int sw,int sh){Minecraft mc=Minecraft.getInstance();if(mc==null)return;if(!dragUndoRecorded){checkpoint();dragUndoRecorded=true;}double worldX=camX+(mc.mouseHandler.getScaledXPos(mc.getWindow())-sw/2.0)/scale,worldZ=camZ+(mc.mouseHandler.getScaledYPos(mc.getWindow())-sh/2.0)/scale;Draft d=draft();if(dragStation>=0){for(int i=0;i<d.stations.size();i++){Station s=d.stations.get(i);if(s.id!=dragStation)continue;double nx=blockCenter(worldX),nz=blockCenter(worldZ);d.stations.set(i,new Station(s.id,s.name,s.type,nx,s.y,nz));for(Branch b:d.branches)if(b.stationIds.contains(s.id))for(int v=0;v<b.vertices.size();v++){Point p=b.vertices.get(v);if(p.x==s.x&&p.z==s.z)b.vertices.set(v,new Point(nx,nz));}break;}}else if(dragBranch>=0&&dragBranch<d.branches.size()){Branch b=d.branches.get(dragBranch);if(dragVertex>=0&&dragVertex<b.vertices.size()){Point old=b.vertices.get(dragVertex),next=new Point(blockCenter(worldX),blockCenter(worldZ));b.vertices.set(dragVertex,next);moveLinkedPoint(d,old,next);}}}
    private static void moveLinkedPoint(Draft d,Point old,Point next){for(Branch b:d.branches)for(int i=0;i<b.links.size();i++){Link link=b.links.get(i);Point a=link.a.equals(old)?next:link.a,c=link.b.equals(old)?next:link.b;if(a!=link.a||c!=link.b)b.links.set(i,new Link(a,c));}}
    public static boolean release(){Minecraft mc=Minecraft.getInstance();double mx=mc==null?gestureStartX:mc.mouseHandler.getScaledXPos(mc.getWindow()),my=mc==null?gestureStartY:mc.mouseHandler.getScaledYPos(mc.getWindow());if(dragging){dragging=false;dragArmed=false;dragUndoRecorded=false;dragStation=dragBranch=dragVertex=-1;saveLibraryQuiet();return true;}if(dragArmed){dragArmed=false;dragStation=dragBranch=dragVertex=-1;return true;}if(!pendingPlacement)return false;pendingPlacement=false;if(movedBeyondClickThreshold(gestureStartX,gestureStartY,mx,my))return false;Point p=snapPoint(draft(),branch(),pendingWorldX,pendingWorldZ);if(pointConnecting)finishPointConnection(p);else place(p.x,p.z);return shouldConsumeRelease(false);}
    private static void armPlacement(double mx,double my,double worldX,double worldZ){dragArmed=false;pendingPlacement=true;gestureStartX=mx;gestureStartY=my;pendingWorldX=worldX;pendingWorldZ=worldZ;}
    private static void armDrag(DragHit hit,double mx,double my){pendingPlacement=false;dragArmed=true;dragging=false;dragUndoRecorded=false;gestureStartX=mx;gestureStartY=my;dragStation=hit.station;dragBranch=hit.branch;dragVertex=hit.vertex;}
    private static void updateDragGesture(){if(!dragArmed||dragging)return;Minecraft mc=Minecraft.getInstance();if(mc==null)return;double mx=mc.mouseHandler.getScaledXPos(mc.getWindow()),my=mc.mouseHandler.getScaledYPos(mc.getWindow());if(movedBeyondClickThreshold(gestureStartX,gestureStartY,mx,my)){dragging=true;dragArmed=false;}}
    static boolean movedBeyondClickThreshold(double startX,double startY,double x,double y){double dx=x-startX,dy=y-startY;return dx*dx+dy*dy>16;}static boolean shouldConsumeRelease(boolean plannerObjectGesture){return plannerObjectGesture;}

    public static boolean click(double mx,double my,double worldX,double worldZ,int sw){if(!active)return false;if(clickMarkerPanel(mx,my,sw))return true;int x=sw-W-8,y=8,py=(int)my-y;if(draftDropdown){int row=(py-46)/ROW,index=firstVisibleDraft()+row;if(mx>=x+8&&mx<=x+W-8&&py>=46&&row>=0&&row<visibleDraftCount()&&index<drafts.size()){saveLibraryQuiet();draftIndex=index;draftDropdown=false;clearMarkerSelection();notice("Opened "+draft().name);return true;}draftDropdown=false;}if(toolDropdown){int chosen=(py-94)/ROW;if(mx>=x+8&&mx<=x+W-8&&py>=94&&chosen>=0&&chosen<TYPES.length){tool=chosen;toolDropdown=false;return true;}toolDropdown=false;}if(mx>=x&&mx<=x+W&&my>=y&&my<=y+panelHeight()){if(py>=26&&py<46)draftDropdown=!draftDropdown;else if(py>=50&&py<70)newDraft();else if(py>=74&&py<94)toolDropdown=!toolDropdown;else if(py>=100&&py<120)coordinateField=1;else if(py>=124&&py<144)coordinateField=2;else if(py>=148&&py<168)coordinateField=3;else if(py>=172&&py<192)placeCoordinates();else if(py>=196&&py<216)placeAtPlayer();else if(py>=220&&py<240){checkpoint();draft().showMarkerInfo=!draft().showMarkerInfo;syncCoordinateMode(draft());saveLibraryQuiet();}else if(py>=254&&py<254+visibleBranchCount()*ROW){int index=firstVisibleBranch()+(py-254)/ROW;if(index<draft().branches.size()){draft().branch=index;clearMarkerSelection();branchPanel=true;}}else{int actions=254+visibleBranchCount()*ROW;if(py>=actions&&py<actions+20)newBranch();else if(py>=actions+24&&py<actions+44)deleteBranch();else if(py>=actions+48&&py<actions+68)undo();else if(py>=actions+72&&py<actions+92)redo();else if(py>=actions+96&&py<actions+116)saveLibrary();else if(py>=actions+120&&py<actions+140)export();else if(py>=actions+144&&py<actions+164)exportImage();else if(py>=actions+168&&py<actions+188)deleteDraft();}return true;}coordinateField=0;DragHit hit=nearestHit(mx,my);if(hit!=null){if(hit.station>=0){if(selectedMarker!=hit.station)selectMarker(hit.station);armDrag(hit,mx,my);return true;}else if(pointConnecting){connectExistingPoint(hit);return true;}else{selectPoint(hit);armDrag(hit,mx,my);return true;}}SegmentHit segment=nearestSegment(mx,my);if(segment!=null){selectSegment(segment,mx,my);return true;}armPlacement(mx,my,worldX,worldZ);return false;}

    private static void panel(GuiGraphicsExtractor g,int sw){Draft d=draft();int x=sw-W-8,y=8;g.fill(x,y,x+W,y+panelHeight(),0xF20A1419);g.text(Minecraft.getInstance().font,"Ice Highway Planner",x+8,y+8,0xFFFFFFFF,false);button(g,x+8,y+26,W-16,"Save: "+d.name+" ▼");button(g,x+8,y+50,W-16,"New draft ("+drafts.size()+" saved)");button(g,x+8,y+74,W-16,"Tool: "+LABELS[tool]+" ▼");field(g,x+8,y+100,W-16,"X",coordinateX,coordinateField==1);field(g,x+8,y+124,W-16,"Y / road height",coordinateY,coordinateField==2);field(g,x+8,y+148,W-16,"Z",coordinateZ,coordinateField==3);button(g,x+8,y+172,W-16,"Place exact coordinates");button(g,x+8,y+196,W-16,"Place at current position");button(g,x+8,y+220,W-16,"Coordinates: "+COORDINATE_MODES[d.coordinateMode]);g.text(Minecraft.getInstance().font,"Drag markers/vertices · line drag snaps",x+8,y+245,0xFF8FD9FF,false);int by=y+254,start=firstVisibleBranch();for(int row=0;row<visibleBranchCount();row++){int i=start+row;Branch b=d.branches.get(i);button(g,x+8,by+row*ROW,W-16,(i==d.branch?"> ":"  ")+b.name+"  · Y"+number(b.y)+" · "+b.vertices.size()+" pts");}int ay=by+visibleBranchCount()*ROW;button(g,x+8,ay,W-16,"+ New branch");button(g,x+8,ay+24,W-16,"Delete selected branch");button(g,x+8,ay+48,W-16,"Undo last point");button(g,x+8,ay+72,W-16,"Save this draft");button(g,x+8,ay+96,W-16,"Export website JSON");button(g,x+8,ay+120,W-16,"Export map image");button(g,x+8,ay+144,W-16,"Delete this draft");if(toolDropdown)for(int i=0;i<TYPES.length;i++)button(g,x+8,y+94+i*ROW,W-16,(i==tool?"> ":"  ")+LABELS[i]);if(draftDropdown){int startDraft=firstVisibleDraft();for(int row=0;row<visibleDraftCount();row++){int i=startDraft+row;button(g,x+8,y+46+row*ROW,W-16,(i==draftIndex?"> ":"  ")+drafts.get(i).name);}}if(System.currentTimeMillis()<feedbackUntil)g.text(Minecraft.getInstance().font,feedback,x+8,y+panelHeight()+4,0xFFFFFF77,false);}
    private static void actionOverlay(GuiGraphicsExtractor g,int sw){int x=sw-W-8,y=8+254+visibleBranchCount()*ROW+48;g.fill(x+8,y,x+W-8,y+140,0xFF0A1419);button(g,x+8,y,W-16,"Undo last change");button(g,x+8,y+24,W-16,"Redo last change");button(g,x+8,y+48,W-16,"Save this draft");button(g,x+8,y+72,W-16,"Export website JSON");button(g,x+8,y+96,W-16,"Export map image");button(g,x+8,y+120,W-16,"Delete this draft");}
    private static int visibleBranchCount(){return Math.min(MAX_BRANCH_ROWS,draft().branches.size());}private static int firstVisibleBranch(){Draft d=draft();return Math.clamp(d.branch-MAX_BRANCH_ROWS+1,0,Math.max(0,d.branches.size()-MAX_BRANCH_ROWS));}private static int panelHeight(){return 254+visibleBranchCount()*ROW+192;}
    private static int visibleDraftCount(){return Math.min(8,drafts.size());}private static int firstVisibleDraft(){return Math.clamp(draftIndex-7,0,Math.max(0,drafts.size()-8));}
    private static void button(GuiGraphicsExtractor g,int x,int y,int w,String text){g.fill(x,y,x+w,y+18,0xFF20343D);g.fill(x,y+16,x+w,y+18,0xFF4E7180);g.centeredText(Minecraft.getInstance().font,text,x+w/2,y+5,0xFFFFFFFF);}
    private static void field(GuiGraphicsExtractor g,int x,int y,int w,String label,String value,boolean focused){g.fill(x,y,x+w,y+18,focused?0xFF315E70:0xFF17262D);g.fill(x,y+16,x+w,y+18,focused?0xFF7EDCF2:0xFF4E7180);g.text(Minecraft.getInstance().font,label+": "+value+(focused?"_":""),x+6,y+5,0xFFFFFFFF,false);}
    public static boolean keyPressed(int key){if(!active)return false;if(pointConnecting&&key==GLFW.GLFW_KEY_ESCAPE){cancelPointConnection();return true;}if(nameEditing!=0){if(key==GLFW.GLFW_KEY_ESCAPE)cancelNameEdit();else if(key==GLFW.GLFW_KEY_ENTER||key==GLFW.GLFW_KEY_KP_ENTER)applyNameEdit();else if(key==GLFW.GLFW_KEY_BACKSPACE&&!nameInput.isEmpty())nameInput=nameInput.substring(0,nameInput.length()-1);return true;}if(coordinateField==0)return false;if(key==GLFW.GLFW_KEY_ESCAPE){coordinateField=0;return true;}if(key==GLFW.GLFW_KEY_TAB){coordinateField=coordinateField%3+1;return true;}if(key==GLFW.GLFW_KEY_ENTER||key==GLFW.GLFW_KEY_KP_ENTER){placeCoordinates();return true;}if(key==GLFW.GLFW_KEY_BACKSPACE){if(coordinateField==1&&!coordinateX.isEmpty())coordinateX=coordinateX.substring(0,coordinateX.length()-1);if(coordinateField==2&&!coordinateY.isEmpty())coordinateY=coordinateY.substring(0,coordinateY.length()-1);if(coordinateField==3&&!coordinateZ.isEmpty())coordinateZ=coordinateZ.substring(0,coordinateZ.length()-1);return true;}return true;}
    public static boolean charTyped(char c){if(!active)return false;if(nameEditing!=0){if(!Character.isISOControl(c)&&nameInput.length()<40)nameInput+=c;return true;}if(coordinateField==0)return false;if((c>='0'&&c<='9')||c=='-'||c=='.'){if(coordinateField==1&&coordinateX.length()<16)coordinateX+=c;if(coordinateField==2&&coordinateY.length()<16)coordinateY+=c;if(coordinateField==3&&coordinateZ.length()<16)coordinateZ+=c;}return true;}
    private static void markerPanel(GuiGraphicsExtractor g,int sw){Station s=selectedStation();if(s==null)return;int x=markerPanelX(sw),y=8;g.fill(x,y,x+W,y+170,0xF20A1419);g.text(Minecraft.getInstance().font,"Selected marker",x+8,y+8,0xFFFFFFFF,false);g.text(Minecraft.getInstance().font,s.name+" · "+labelForType(s.type),x+8,y+24,0xFFFFD36A,false);g.text(Minecraft.getInstance().font,"XYZ "+number(s.x)+", "+number(s.y)+", "+number(s.z),x+8,y+38,0xFFB9DDEB,false);button(g,x+8,y+54,W-16,markerEditing?"Finish editing":"Edit marker");button(g,x+8,y+78,W-16,"Apply X / Y / Z fields");button(g,x+8,y+102,W-16,"Rename marker");button(g,x+8,y+126,W-16,"Delete marker");button(g,x+8,y+150,W-16,"Close");}
    private static void segmentPanel(GuiGraphicsExtractor g,int sw){if(!validSelectedSegment())return;drawSelectedSegmentHandles(g);Branch b=draft().branches.get(selectedSegmentBranch);Point a=b.vertices.get(selectedSegment),c=b.vertices.get(selectedSegment+1);int x=markerPanelX(sw),y=8;g.fill(x,y,x+W,y+256,0xF20A1419);g.text(Minecraft.getInstance().font,"Selected line segment",x+8,y+8,0xFFFFFFFF,false);g.text(Minecraft.getInstance().font,b.name+" #"+(selectedSegment+1),x+8,y+24,0xFFFFFF55,false);g.text(Minecraft.getInstance().font,number(a.x)+", "+number(a.z)+" to "+number(c.x)+", "+number(c.z),x+8,y+38,0xFFB9DDEB,false);if(segmentEditing)g.text(Minecraft.getInstance().font,"Drag either endpoint to resize",x+8,y+51,0xFF8FD9FF,false);button(g,x+8,y+68,W-16,segmentEditing?"Finish editing":"Edit endpoints");button(g,x+8,y+92,W-16,"Add point where clicked");button(g,x+8,y+116,W-16,"Remove start point");button(g,x+8,y+140,W-16,"Remove end point");button(g,x+8,y+164,W-16,"Remove connection");button(g,x+8,y+188,W-16,"Add connecting points");button(g,x+8,y+212,W-16,"Separate branch here");button(g,x+8,y+236,W-16,"Close");}
    private static void drawSelectedSegmentHandles(GuiGraphicsExtractor g){for(SegmentHit hit:segmentHits)if(hit.branch==selectedSegmentBranch&&hit.segment==selectedSegment){int color=segmentEditing?0xFFFFFFFF:0xFFFFFF55;drawHandle(g,(int)Math.round(hit.ax),(int)Math.round(hit.ay),color);drawHandle(g,(int)Math.round(hit.bx),(int)Math.round(hit.by),color);return;}}private static void drawHandle(GuiGraphicsExtractor g,int x,int y,int color){g.fill(x-4,y-4,x+5,y+5,0xFF071014);g.fill(x-2,y-2,x+3,y+3,color);}
    private static void drawPlannerPoints(GuiGraphicsExtractor g,List<DragHit> hits,int sw,int sh,Set<String> topologyLabels){Draft d=draft();Set<String>drawn=new HashSet<>();List<int[]>occupied=new ArrayList<>();for(DragHit hit:hits)if(hit.station<0&&hit.branch>=0&&hit.branch<d.branches.size()){Branch b=d.branches.get(hit.branch);if(hit.vertex<0||hit.vertex>=b.vertices.size())continue;Point p=b.vertices.get(hit.vertex);boolean selected=!TownyMapMod.composingPlannerExport()&&hit.branch==selectedPointBranch&&hit.vertex==selectedPoint;int color=selected?0xFFFFFF55:pointConnecting&&!TownyMapMod.composingPlannerExport()?0xFF77FFAA:0xFFB9DDEB;int x=(int)Math.round(hit.x),y=(int)Math.round(hit.y);g.fill(x-3,y-3,x+4,y+4,0xCC071014);g.fill(x-1,y-1,x+2,y+2,color);if(!showPointCoordinate(d,b,p,topologyLabels))continue;String text=number(p.x)+", "+number(b.y)+", "+number(p.z),key=number(p.x)+"|"+number(b.y)+"|"+number(p.z);if(drawn.add(key))placePointLabel(g,x,y,text,color,occupied,sw,sh);}}
    private static void syncCoordinateMode(Draft d){d.coordinateMode=(d.coordinateMode+1)%COORDINATE_MODES.length;d.showMarkerInfo=d.coordinateMode!=3&&d.coordinateMode!=4;notice("Coordinates: "+COORDINATE_MODES[d.coordinateMode]);}
    private static String stationLabel(Draft d,Station s,boolean export){boolean coordinates=d.coordinateMode==0||d.coordinateMode==2;return s.name+(coordinates?"  "+number(s.x)+", "+number(s.y)+", "+number(s.z):"");}
    private static boolean showPointCoordinate(Draft d,Branch b,Point p,Set<String> topologyLabels){if(d.coordinateMode==0)return true;if(d.coordinateMode!=1)return false;return topologyLabels.contains(pointHeightKey(p,b.y));}
    static boolean shouldShowTopologyCoordinate(int connections,boolean turn,boolean yChange){return yChange||connections<=2&&turn;}
    private static Set<String> topologyCoordinateKeys(Draft d){Map<Point,Set<Point>> adjacency=new HashMap<>();Map<Point,Set<Double>> heights=new HashMap<>();List<Link> links=new ArrayList<>();for(Branch b:d.branches){for(Point p:b.vertices)heights.computeIfAbsent(p,ignored->new HashSet<>()).add(b.y);for(int i=1;i<b.vertices.size();i++)if(!b.breaks.contains(i))connectTopology(adjacency,b.vertices.get(i-1),b.vertices.get(i));links.addAll(b.links);}for(Link link:links)connectTopology(adjacency,link.a,link.b);Set<Point>heightChanges=new HashSet<>();for(var entry:heights.entrySet())if(entry.getValue().size()>1)heightChanges.add(entry.getKey());for(Link link:links){Set<Double> a=heights.getOrDefault(link.a,Set.of()),b=heights.getOrDefault(link.b,Set.of());if(!Collections.disjoint(a,b))continue;heightChanges.add(link.a);heightChanges.add(link.b);}Set<String> labels=new HashSet<>();for(Branch branch:d.branches)for(Point p:branch.vertices){Set<Point> neighbors=adjacency.getOrDefault(p,Set.of());boolean turn=false;if(neighbors.size()==2){Iterator<Point> it=neighbors.iterator();turn=isCorner(it.next(),p,it.next());}if(shouldShowTopologyCoordinate(neighbors.size(),turn,heightChanges.contains(p)))labels.add(pointHeightKey(p,branch.y));}return labels;}
    private static void connectTopology(Map<Point,Set<Point>> adjacency,Point a,Point b){if(a.equals(b))return;adjacency.computeIfAbsent(a,ignored->new HashSet<>()).add(b);adjacency.computeIfAbsent(b,ignored->new HashSet<>()).add(a);}
    private static String pointHeightKey(Point p,double y){return Double.doubleToLongBits(p.x)+":"+Double.doubleToLongBits(y)+":"+Double.doubleToLongBits(p.z);}
    private static void placePointLabel(GuiGraphicsExtractor g,int x,int y,String text,int color,List<int[]>occupied,int sw,int sh){int width=Minecraft.getInstance().font.width(text)+4;for(int dy:LABEL_VERTICAL_OFFSETS)for(int side=0;side<2;side++){int left=side==0?x+8:x-width-8,top=y+dy,right=left+width,bottom=top+12;if(left<2||top<2||right>sw-2||bottom>sh-2)continue;boolean collision=false;for(int[]r:occupied)if(rectanglesOverlap(left,top,right,bottom,r[0],r[1],r[2],r[3])){collision=true;break;}if(!collision){occupied.add(new int[]{left,top,right,bottom});g.fill(left,top,right,bottom,0xCC071014);g.text(Minecraft.getInstance().font,text,left+2,top+2,color,false);return;}}}
    static boolean rectanglesOverlap(int l1,int t1,int r1,int b1,int l2,int t2,int r2,int b2){return l1<r2&&r1>l2&&t1<b2&&b1>t2;}
    private static void pointPanel(GuiGraphicsExtractor g,int sw){if(!validSelectedPoint())return;Point p=selectedPointValue();int x=markerPanelX(sw),y=8;g.fill(x,y,x+W,y+184,0xF20A1419);g.text(Minecraft.getInstance().font,pointConnecting?"Connection source selected":"Selected line point",x+8,y+8,pointConnecting?0xFF77FFAA:0xFFFFFFFF,false);g.text(Minecraft.getInstance().font,branch().name+" · XYZ "+number(p.x)+", "+number(branch().y)+", "+number(p.z),x+8,y+26,0xFFFFFF55,false);if(pointConnecting)g.text(Minecraft.getInstance().font,"Click an existing or new point",x+8,y+40,0xFF77FFAA,false);button(g,x+8,y+54,W-16,pointEditing?"Finish moving point":"Move point");button(g,x+8,y+78,W-16,"Apply exact X / Y / Z");button(g,x+8,y+102,W-16,pointConnecting?"Cancel connection":"Connect from selected point");button(g,x+8,y+126,W-16,"Remove point");button(g,x+8,y+150,W-16,"Close");}
    private static void branchPanel(GuiGraphicsExtractor g,int sw){if(!branchPanel)return;Branch b=branch();int x=markerPanelX(sw),y=8;g.fill(x,y,x+W,y+170,0xF20A1419);g.text(Minecraft.getInstance().font,"Selected branch",x+8,y+8,0xFFFFFFFF,false);g.text(Minecraft.getInstance().font,draft().line+" · "+b.name,x+8,y+26,0xFF8FD9FF,false);button(g,x+8,y+46,W-16,"Start new line on branch");button(g,x+8,y+70,W-16,"Rename branch");button(g,x+8,y+94,W-16,"Rename line");button(g,x+8,y+118,W-16,"Merge nearest branch");button(g,x+8,y+142,W-16,"Close");}
    private static void namePanel(GuiGraphicsExtractor g,int sw){if(nameEditing==0)return;int x=markerPanelX(sw),y=148;g.fill(x,y,x+W,y+78,0xFA0A1419);g.text(Minecraft.getInstance().font,"Rename "+nameKind(),x+8,y+8,0xFFFFFFFF,false);field(g,x+8,y+26,W-16,"Name",nameInput,true);button(g,x+8,y+50,(W-20)/2,"Apply");button(g,x+12+(W-20)/2,y+50,(W-20)/2,"Cancel");}
    private static int markerPanelX(int sw){return Math.max(8,sw-W*2-20);}private static Station selectedStation(){for(Station s:draft().stations)if(s.id==selectedMarker)return s;return null;}private static String labelForType(String type){for(int i=1;i<TYPES.length;i++)if(TYPES[i].equals(type))return LABELS[i];return type;}
    private static boolean clickMarkerPanel(double mx,double my,int sw){if(clickNamePanel(mx,my,sw)||clickBranchPanel(mx,my,sw)||clickPointPanel(mx,my,sw)||clickSegmentPanel(mx,my,sw))return true;Station s=selectedStation();if(s==null)return false;int x=markerPanelX(sw),y=8;if(mx<x||mx>x+W||my<y||my>y+170)return false;int py=(int)my-y;if(py>=54&&py<74){markerEditing=!markerEditing;if(markerEditing)loadMarkerCoordinates(s);notice(markerEditing?"Drag the marker or enter exact XYZ":"Finished editing marker");}else if(py>=78&&py<98){if(!markerEditing){markerEditing=true;loadMarkerCoordinates(s);}applyMarkerCoordinates();}else if(py>=102&&py<122)startNameEdit(1,s.name);else if(py>=126&&py<146)deleteSelectedMarker();else if(py>=150&&py<170)clearMarkerSelection();return true;}
    private static boolean clickPointPanel(double mx,double my,int sw){if(!validSelectedPoint())return false;int x=markerPanelX(sw),y=8;if(mx<x||mx>x+W||my<y||my>y+184)return false;int py=(int)my-y;if(py>=54&&py<74){pointEditing=!pointEditing;notice(pointEditing?"Drag the selected point":"Finished moving point");}else if(py>=78&&py<98)applySelectedPointCoordinates();else if(py>=102&&py<122){if(pointConnecting)cancelPointConnection();else beginPointConnection();}else if(py>=126&&py<146)deleteSelectedPoint();else if(py>=150&&py<170)clearPointSelection();return true;}
    private static boolean clickSegmentPanel(double mx,double my,int sw){if(!validSelectedSegment())return false;int x=markerPanelX(sw),y=8;if(mx<x||mx>x+W||my<y||my>y+256)return false;int py=(int)my-y;if(py>=68&&py<88){segmentEditing=!segmentEditing;if(segmentEditing)tool=0;notice(segmentEditing?"Drag either endpoint to extend or retract":"Finished editing segment");}else if(py>=92&&py<112)addPointToSelectedSegment();else if(py>=116&&py<136)removeSelectedPoint(false);else if(py>=140&&py<160)removeSelectedPoint(true);else if(py>=164&&py<184)removeSelectedSegment();else if(py>=188&&py<208)continueFromSelectedSegment();else if(py>=212&&py<232)separateSelectedBranch();else if(py>=236&&py<256)clearSegmentSelection();return true;}
    private static boolean clickBranchPanel(double mx,double my,int sw){if(!branchPanel)return false;int x=markerPanelX(sw),y=8;if(mx<x||mx>x+W||my<y||my>y+170)return false;int py=(int)my-y;if(py>=46&&py<66)startNewLine();else if(py>=70&&py<90)startNameEdit(2,branch().name);else if(py>=94&&py<114)startNameEdit(3,draft().line);else if(py>=118&&py<138)mergeNearestBranch();else if(py>=142&&py<162)branchPanel=false;return true;}
    private static boolean clickNamePanel(double mx,double my,int sw){if(nameEditing==0)return false;int x=markerPanelX(sw),y=148;if(mx<x||mx>x+W||my<y||my>y+78)return true;if(my>=y+50&&my<y+70){if(mx<x+W/2)applyNameEdit();else cancelNameEdit();}return true;}
    private static boolean validSelectedSegment(){return selectedSegmentBranch>=0&&selectedSegmentBranch<draft().branches.size()&&selectedSegment>=0&&selectedSegment+1<draft().branches.get(selectedSegmentBranch).vertices.size()&&!draft().branches.get(selectedSegmentBranch).breaks.contains(selectedSegment+1);}private static void selectSegment(SegmentHit hit,double mx,double my){clearMarkerSelection();selectedSegmentBranch=hit.branch;selectedSegment=hit.segment;segmentEditing=false;draft().branch=hit.branch;Branch b=branch();Point a=b.vertices.get(hit.segment),c=b.vertices.get(hit.segment+1);double dx=hit.bx-hit.ax,dy=hit.by-hit.ay,q=dx*dx+dy*dy,t=q==0?.5:Math.clamp(((mx-hit.ax)*dx+(my-hit.ay)*dy)/q,0,1);selectedSegmentPoint=new Point(blockCenter(a.x+(c.x-a.x)*t),blockCenter(a.z+(c.z-a.z)*t));}private static void clearSegmentSelection(){selectedSegmentBranch=selectedSegment=-1;selectedSegmentPoint=null;segmentEditing=false;}
    private static boolean validSelectedPoint(){return selectedPointBranch>=0&&selectedPointBranch<draft().branches.size()&&selectedPoint>=0&&selectedPoint<draft().branches.get(selectedPointBranch).vertices.size();}private static Point selectedPointValue(){return validSelectedPoint()?draft().branches.get(selectedPointBranch).vertices.get(selectedPoint):null;}private static void selectPoint(DragHit hit){clearMarkerSelection();selectedPointBranch=hit.branch;selectedPoint=hit.vertex;draft().branch=hit.branch;pointEditing=false;Point p=selectedPointValue();coordinateX=number(p.x);coordinateY=number(branch().y);coordinateZ=number(p.z);}private static void clearPointSelection(){selectedPointBranch=selectedPoint=-1;pointEditing=false;pointConnecting=false;connectionStart=null;}
    private static void applySelectedPointCoordinates(){if(!validSelectedPoint())return;try{double x=blockCenter(Double.parseDouble(coordinateX)),y=Double.parseDouble(coordinateY),z=blockCenter(Double.parseDouble(coordinateZ));if(!Double.isFinite(x)||!Double.isFinite(y)||!Double.isFinite(z))throw new NumberFormatException();checkpoint();Branch b=draft().branches.get(selectedPointBranch);Point old=b.vertices.get(selectedPoint),next=new Point(x,z);b.vertices.set(selectedPoint,next);moveLinkedPoint(draft(),old,next);b.y=y;coordinateField=0;saveLibraryQuiet();notice("Updated point XYZ to "+number(x)+", "+number(y)+", "+number(z));}catch(NumberFormatException e){notice("Enter valid X, Y and Z");}}
    private static void beginPointConnection(){Point p=selectedPointValue();if(p==null)return;connectionStart=p;pointConnecting=true;pointEditing=false;tool=0;notice("Source selected; click an existing or new point");}
    private static void cancelPointConnection(){pointConnecting=false;connectionStart=null;notice("Connection cancelled");}
    private static void connectExistingPoint(DragHit targetHit){if(connectionStart==null||targetHit.station>=0)return;Point target=draft().branches.get(targetHit.branch).vertices.get(targetHit.vertex);if(target.equals(connectionStart)){notice("Choose a different point");return;}Branch owner=draft().branches.get(selectedPointBranch);for(Link link:owner.links)if(link.a.equals(connectionStart)&&link.b.equals(target)||link.a.equals(target)&&link.b.equals(connectionStart)){cancelPointConnection();notice("Those points are already connected");return;}checkpoint();owner.links.add(new Link(connectionStart,target));pointConnecting=false;connectionStart=null;coordinateX=number(selectedPointValue().x);coordinateY=number(owner.y);coordinateZ=number(selectedPointValue().z);saveLibraryQuiet();notice("Connected points; original source remains selected");}
    private static void finishPointConnection(Point target){if(connectionStart==null||!validSelectedPoint())return;target=new Point(blockCenter(target.x),blockCenter(target.z));if(target.equals(connectionStart)){notice("Choose a different point");return;}checkpoint();Branch b=draft().branches.get(selectedPointBranch);int source=selectedPoint;boolean runStart=source==0||b.breaks.contains(source),runEnd=source==b.vertices.size()-1||b.breaks.contains(source+1);if(runEnd)insertPoint(b,source+1,target);else if(runStart){insertPoint(b,source,target);if(source>0){b.breaks.remove(source+1);b.breaks.add(source);}selectedPoint=source+1;}else{insertPoint(b,source+1,target);b.breaks.add(source+2);}pointConnecting=false;connectionStart=null;Point selected=selectedPointValue();coordinateX=number(selected.x);coordinateY=number(b.y);coordinateZ=number(selected.z);saveLibraryQuiet();notice("Connected new line; original source remains selected");}
    private static void deleteSelectedPoint(){if(!validSelectedPoint())return;checkpoint();Branch b=draft().branches.get(selectedPointBranch);removePoint(b,selectedPoint);clearPointSelection();saveLibraryQuiet();notice("Removed line point");}
    private static void addPointToSelectedSegment(){if(!validSelectedSegment()||selectedSegmentPoint==null)return;Branch b=draft().branches.get(selectedSegmentBranch);Point a=b.vertices.get(selectedSegment),c=b.vertices.get(selectedSegment+1);if(selectedSegmentPoint.equals(a)||selectedSegmentPoint.equals(c)){notice("Click farther from an endpoint");return;}checkpoint();insertPoint(b,selectedSegment+1,selectedSegmentPoint);selectedSegment++;saveLibraryQuiet();notice("Added point at "+number(selectedSegmentPoint.x)+", "+number(selectedSegmentPoint.z));}
    private static void removeSelectedPoint(boolean end){if(!validSelectedSegment())return;checkpoint();Branch b=draft().branches.get(selectedSegmentBranch);removePoint(b,selectedSegment+(end?1:0));clearSegmentSelection();saveLibraryQuiet();notice("Removed line point");}
    private static void removeSelectedSegment(){if(!validSelectedSegment())return;checkpoint();Branch b=draft().branches.get(selectedSegmentBranch);b.breaks.add(selectedSegment+1);clearSegmentSelection();saveLibraryQuiet();notice("Removed connection; branch remains merged");}
    private static void insertPoint(Branch b,int index,Point point){NavigableSet<Integer>shifted=new TreeSet<>();for(int at:b.breaks)shifted.add(at>=index?at+1:at);b.breaks.clear();b.breaks.addAll(shifted);b.vertices.add(index,point);}
    private static void removePoint(Branch b,int index){boolean preserveGap=b.breaks.contains(index)||b.breaks.contains(index+1);NavigableSet<Integer>shifted=new TreeSet<>();for(int at:b.breaks)if(at<index)shifted.add(at);else if(at>index+1)shifted.add(at-1);b.vertices.remove(index);if(preserveGap&&index>0&&index<b.vertices.size())shifted.add(index);b.breaks.clear();b.breaks.addAll(shifted);}
    private static void startNewLine(){tool=0;newLinePending=true;branchPanel=false;notice("Click the first point of the new line");}
    private static void continueFromSelectedSegment(){if(!validSelectedSegment())return;checkpoint();Branch b=draft().branches.get(selectedSegmentBranch);Point start=b.vertices.get(selectedSegment+1);b.breaks.add(b.vertices.size());b.vertices.add(start);draft().branch=selectedSegmentBranch;tool=0;newLinePending=false;clearSegmentSelection();saveLibraryQuiet();notice("Click to add connecting points");}
    private static void separateSelectedBranch(){if(!validSelectedSegment())return;Draft d=draft();Branch left=d.branches.get(selectedSegmentBranch);int split=selectedSegment+1;if(split>=left.vertices.size()-1){notice("Choose an interior segment to separate");return;}checkpoint();Branch right=new Branch(uniqueBranchName(d,left.name+" Split"));right.y=left.y;right.vertices.addAll(new ArrayList<>(left.vertices.subList(split,left.vertices.size())));left.vertices.subList(split+1,left.vertices.size()).clear();Set<Point>rightPoints=new HashSet<>(right.vertices);for(Station s:d.stations)if(left.stationIds.contains(s.id)&&rightPoints.contains(new Point(s.x,s.z))){left.stationIds.remove((Integer)s.id);right.stationIds.add(s.id);}d.branches.add(selectedSegmentBranch+1,right);d.branch=selectedSegmentBranch+1;clearSegmentSelection();branchPanel=true;saveLibraryQuiet();notice("Separated into "+left.name+" and "+right.name);}
    private static void mergeNearestBranch(){Draft d=draft();if(d.branches.size()<2||branch().vertices.isEmpty()){notice("Another non-empty branch is required");return;}int sourceIndex=d.branch,targetIndex=-1;Branch source=branch();boolean reverseSource=false,reverseTarget=false;double best=Double.POSITIVE_INFINITY;for(int i=0;i<d.branches.size();i++){if(i==sourceIndex||d.branches.get(i).vertices.isEmpty())continue;Branch target=d.branches.get(i);for(int se=0;se<2;se++)for(int te=0;te<2;te++){Point a=se==0?source.vertices.getFirst():source.vertices.getLast(),b=te==0?target.vertices.getFirst():target.vertices.getLast();double q=distance2(a.x,a.z,b.x,b.z);if(q<best){best=q;targetIndex=i;reverseSource=se==0;reverseTarget=te==1;}}}if(targetIndex<0){notice("Another non-empty branch is required");return;}checkpoint();Branch target=d.branches.get(targetIndex);if(reverseSource)Collections.reverse(source.vertices);List<Point>tail=new ArrayList<>(target.vertices);if(reverseTarget)Collections.reverse(tail);if(!source.vertices.getLast().equals(tail.getFirst()))source.vertices.add(tail.getFirst());source.vertices.addAll(tail.subList(1,tail.size()));for(Integer id:target.stationIds)if(!source.stationIds.contains(id))source.stationIds.add(id);String targetName=target.name;d.branches.remove(targetIndex);d.branch=targetIndex<sourceIndex?sourceIndex-1:sourceIndex;branchPanel=true;saveLibraryQuiet();notice("Merged "+targetName+" into "+source.name);}
    private static String uniqueBranchName(Draft d,String base){String name=base;int suffix=2;while(hasBranchName(d,name))name=base+" "+suffix++;return name;}private static boolean hasBranchName(Draft d,String name){for(Branch b:d.branches)if(b.name.equals(name))return true;return false;}
    private static void startNameEdit(int kind,String value){nameEditing=kind;nameInput=value;coordinateField=0;}private static String nameKind(){return nameEditing==1?"marker":nameEditing==2?"branch":"line";}private static void cancelNameEdit(){nameEditing=0;nameInput="";}private static void applyNameEdit(){String value=nameInput.trim();if(value.isEmpty()){notice("Name cannot be empty");return;}checkpoint();if(nameEditing==1){Station old=selectedStation();if(old==null){cancelNameEdit();return;}for(int i=0;i<draft().stations.size();i++)if(draft().stations.get(i).id==old.id){draft().stations.set(i,new Station(old.id,value,old.type,old.x,old.y,old.z));break;}}else if(nameEditing==2){if(hasBranchName(draft(),value)&&!branch().name.equals(value)){notice("Branch name already exists");return;}branch().name=value;}else if(nameEditing==3)draft().line=value;String kind=nameKind();cancelNameEdit();saveLibraryQuiet();notice("Renamed "+kind+" to "+value);}
    private static void selectMarker(int id){branchPanel=false;clearSegmentSelection();selectedMarker=id;markerEditing=false;Station s=selectedStation();if(s!=null)loadMarkerCoordinates(s);}
    private static void loadMarkerCoordinates(Station s){coordinateX=number(s.x);coordinateY=number(s.y);coordinateZ=number(s.z);}
    private static void clearMarkerSelection(){selectedMarker=-1;markerEditing=false;clearSegmentSelection();clearPointSelection();pointConnecting=false;connectionStart=null;branchPanel=false;newLinePending=false;cancelNameEdit();dragging=false;dragUndoRecorded=false;dragStation=dragBranch=dragVertex=-1;}
    private static void applyMarkerCoordinates(){Station old=selectedStation();if(old==null)return;try{double x=blockCenter(Double.parseDouble(coordinateX)),y=Double.parseDouble(coordinateY),z=blockCenter(Double.parseDouble(coordinateZ));if(!Double.isFinite(x)||!Double.isFinite(y)||!Double.isFinite(z))throw new NumberFormatException();checkpoint();Draft d=draft();for(int i=0;i<d.stations.size();i++)if(d.stations.get(i).id==old.id){d.stations.set(i,new Station(old.id,old.name,old.type,x,y,z));break;}for(Branch b:d.branches)if(b.stationIds.contains(old.id))for(int i=0;i<b.vertices.size();i++){Point p=b.vertices.get(i);if(p.x==old.x&&p.z==old.z)b.vertices.set(i,new Point(x,z));}coordinateField=0;saveLibraryQuiet();notice("Updated marker to "+number(x)+", "+number(y)+", "+number(z));}catch(NumberFormatException e){notice("Enter valid X, Y and Z");}}
    private static void deleteSelectedMarker(){Station s=selectedStation();if(s==null)return;checkpoint();Draft d=draft();d.stations.removeIf(candidate->candidate.id==s.id);for(Branch b:d.branches)b.stationIds.removeIf(id->id==s.id);clearMarkerSelection();saveLibraryQuiet();notice("Deleted "+s.name);}
    private static void placeCoordinates(){if(markerEditing&&selectedStation()!=null){applyMarkerCoordinates();return;}if(shouldEditSelectedPoint(pointEditing)&&validSelectedPoint()){applySelectedPointCoordinates();return;}try{double x=Double.parseDouble(coordinateX),y=Double.parseDouble(coordinateY),z=Double.parseDouble(coordinateZ);if(!Double.isFinite(x)||!Double.isFinite(y)||!Double.isFinite(z))throw new NumberFormatException();if(pointConnecting)finishPointConnection(new Point(x,z));else{placeExact(x,y,z);notice("Placed exact "+x+", "+y+", "+z);}coordinateField=0;}catch(NumberFormatException e){notice("Enter valid X, Y and Z");}}
    private static void placeAtPlayer(){Minecraft mc=Minecraft.getInstance();if(mc==null||mc.player==null){notice("Player position unavailable");return;}double scale=TownyMapMod.dimensionCoordinateScale(),x=mc.player.getX()*scale,y=mc.player.getY(),z=mc.player.getZ()*scale;coordinateX=number(x);coordinateY=number(y);coordinateZ=number(z);if(markerEditing&&selectedStation()!=null)applyMarkerCoordinates();else if(shouldEditSelectedPoint(pointEditing)&&validSelectedPoint())applySelectedPointCoordinates();else if(pointConnecting)finishPointConnection(new Point(x,z));else{placeExact(x,y,z);notice("Placed at "+coordinateX+", "+coordinateY+", "+coordinateZ);}}
    static boolean shouldEditSelectedPoint(boolean editMode){return editMode;}
    private static void place(double x,double z){checkpoint();Draft d=draft();Branch b=branch();double y=parseY();x=blockCenter(x);z=blockCenter(z);if(tool==0){b.y=y;addPoint(b,x,z);}else{int id=nextId(d);d.stations.add(new Station(id,LABELS[tool]+" "+(id+1),TYPES[tool],x,y,z));b.stationIds.add(id);}saveLibraryQuiet();}
    private static void placeExact(double x,double y,double z){checkpoint();Draft d=draft();Branch b=branch();x=blockCenter(x);z=blockCenter(z);if(tool==0){addPoint(b,x,z);b.y=y;}else{int id=nextId(d);d.stations.add(new Station(id,LABELS[tool]+" "+(id+1),TYPES[tool],x,y,z));b.stationIds.add(id);}saveLibraryQuiet();}
    private static double parseY(){try{double y=Double.parseDouble(coordinateY);return Double.isFinite(y)?y:64;}catch(NumberFormatException e){return 64;}}
    /** Default click snapping: marker, segment projection, then an 8-way (45 degree) line direction. */
    static Point snapPoint(Draft d,Branch current,double x,double z){double limit2=32*32,best=limit2;Point snapped=null;for(Station s:d.stations){double q=distance2(x,z,s.x,s.z);if(q<=best){best=q;snapped=new Point(blockCenter(s.x),blockCenter(s.z));}}for(Branch b:d.branches)for(int i=1;i<b.vertices.size();i++){if(b.breaks.contains(i))continue;Point p=project(x,z,b.vertices.get(i-1),b.vertices.get(i));double q=distance2(x,z,p.x,p.z);if(q<=best){best=q;snapped=p;}}if(snapped!=null)return snapped;if(current.vertices.isEmpty())return new Point(blockCenter(x),blockCenter(z));Point from=current.vertices.getLast();double[] p=snapDirection(from.x,from.z,x,z);return new Point(p[0],p[1]);}
    static double[] snapDirection(double fromX,double fromZ,double x,double z){double dx=x-fromX,dz=z-fromZ,length=Math.hypot(dx,dz);if(length==0)return new double[]{blockCenter(fromX),blockCenter(fromZ)};double angle=Math.round(Math.atan2(dz,dx)/(Math.PI/4))*(Math.PI/4);return new double[]{blockCenter(fromX+Math.cos(angle)*length),blockCenter(fromZ+Math.sin(angle)*length)};}
    static double[] projectOntoSegment(double x,double z,double ax,double az,double bx,double bz){Point p=project(x,z,new Point(ax,az),new Point(bx,bz));return new double[]{p.x,p.z};}
    private static Point project(double x,double z,Point a,Point b){double dx=b.x-a.x,dz=b.z-a.z,q=dx*dx+dz*dz,t=q==0?0:Math.clamp(((x-a.x)*dx+(z-a.z)*dz)/q,0,1);return new Point(blockCenter(a.x+dx*t),blockCenter(a.z+dz*t));}private static double distance2(double x,double z,double a,double b){double dx=x-a,dz=z-b;return dx*dx+dz*dz;}
    static boolean isCorner(Point a,Point b,Point c){double x1=b.x-a.x,z1=b.z-a.z,x2=c.x-b.x,z2=c.z-b.z;double cross=x1*z2-z1*x2,dot=x1*x2+z1*z2;return Math.abs(cross)>1e-6||dot<0;}
    private static void previousDraft(){saveLibraryQuiet();draftIndex=Math.floorMod(draftIndex-1,drafts.size());notice("Opened "+draft().name);}private static void nextDraft(){saveLibraryQuiet();draftIndex=(draftIndex+1)%drafts.size();notice("Opened "+draft().name);}
    private static void newDraft(){checkpoint();saveLibraryQuiet();drafts.add(new Draft("Draft "+(drafts.size()+1)));draftIndex=drafts.size()-1;clearMarkerSelection();saveLibraryQuiet();notice("Created "+draft().name);}
    private static void deleteDraft(){checkpoint();String old=draft().name;drafts.remove(draftIndex);if(drafts.isEmpty())drafts.add(new Draft("Draft 1"));draftIndex=Math.clamp(draftIndex,0,drafts.size()-1);clearMarkerSelection();saveLibraryQuiet();notice("Deleted "+old);}
    private static void newBranch(){checkpoint();Draft d=draft();d.branches.add(new Branch("Branch "+(d.branches.size()+1)));d.branch=d.branches.size()-1;tool=0;saveLibraryQuiet();notice("Editing "+branch().name);}
    private static void deleteBranch(){checkpoint();Draft d=draft();Branch removed=branch();Set<Integer>ids=Set.copyOf(removed.stationIds);d.stations.removeIf(s->ids.contains(s.id));if(ids.contains(selectedMarker))clearMarkerSelection();if(d.branches.size()==1){removed.vertices.clear();removed.stationIds.clear();removed.y=64;notice("Cleared "+removed.name);}else{d.branches.remove(d.branch);d.branch=Math.clamp(d.branch,0,d.branches.size()-1);notice("Deleted "+removed.name);}saveLibraryQuiet();}
    private static void checkpoint(){undoHistory.addLast(libraryJson().deepCopy());while(undoHistory.size()>100)undoHistory.removeFirst();redoHistory.clear();}
    private static void undo(){if(undoHistory.isEmpty()){notice("Nothing to undo");return;}redoHistory.addLast(libraryJson().deepCopy());while(redoHistory.size()>100)redoHistory.removeFirst();restoreSnapshot(undoHistory.removeLast());notice("Undid last change");}
    private static void redo(){if(redoHistory.isEmpty()){notice("Nothing to redo");return;}undoHistory.addLast(libraryJson().deepCopy());while(undoHistory.size()>100)undoHistory.removeFirst();restoreSnapshot(redoHistory.removeLast());notice("Redid last change");}
    private static void restoreSnapshot(JsonObject root){drafts.clear();for(JsonElement e:root.getAsJsonArray("drafts"))drafts.add(parseDraft(e.getAsJsonObject()));if(drafts.isEmpty())drafts.add(new Draft("Draft 1"));draftIndex=Math.clamp(root.has("activeDraft")?root.get("activeDraft").getAsInt():0,0,drafts.size()-1);clearMarkerSelection();saveLibraryQuiet();}
    private static int nextId(Draft d){return d.stations.stream().mapToInt(Station::id).max().orElse(-1)+1;}private static void addPoint(Branch b,double x,double z){Point p=new Point(blockCenter(x),blockCenter(z));if(b.vertices.contains(p)){notice("That point already exists; select it to connect");newLinePending=false;return;}addStandalonePoint(b,p);newLinePending=false;}
    static void addStandalonePointForTest(List<double[]> points,NavigableSet<Integer> breaks,double x,double z){int index=points.size();if(index>0)breaks.add(index);points.add(new double[]{blockCenter(x),blockCenter(z)});}
    private static void addStandalonePoint(Branch b,Point p){if(!b.vertices.isEmpty())b.breaks.add(b.vertices.size());b.vertices.add(p);}

    static JsonObject websiteJson(){return websiteJson(draft(),true);}static JsonObject websiteJsonForTest(){return websiteJson(new Draft("Test"),true);}private static JsonObject websiteJson(Draft d,boolean splitRuns){JsonObject root=new JsonObject();JsonArray ss=new JsonArray();for(Station s:d.stations){JsonObject o=new JsonObject();o.addProperty("name",s.name);o.addProperty("id",s.id);if(!"station".equals(s.type))o.addProperty("type",s.type);o.addProperty("x",s.x);o.addProperty("z",s.z);if(s.type.startsWith("elev")){o.addProperty("y1",s.y);o.addProperty("y2",lineHeight(d));}JsonObject company=new JsonObject(),line=new JsonObject();JsonArray membership=new JsonArray();membership.add("");membership.add(websiteBranchMembership(d,s.id));line.add(d.line,membership);company.add(d.company,line);o.add("lines",company);ss.add(o);}root.add("stations",ss);JsonObject lines=new JsonObject(),company=new JsonObject(),route=new JsonObject(),bs=new JsonObject();route.addProperty("prefix",d.prefix);route.addProperty("code",d.code);route.addProperty("color",d.color);route.addProperty("y",lineHeight(d));for(Branch b:d.branches)addBranchJson(bs,d,b,splitRuns);route.add("branches",bs);company.add(d.line,route);lines.add(d.company,company);root.add("lines",lines);return root;}
    private static String branchFor(Draft d,int id){for(Branch b:d.branches)if(b.stationIds.contains(id))return b.name;return "Main";}
    private static double lineHeight(Draft d){return d.branches.isEmpty()?64:d.branches.getFirst().y;}
    private static List<Branch> branchesForStation(Draft d,int id){List<Branch> found=new ArrayList<>();for(Branch b:d.branches)if(b.stationIds.contains(id))found.add(b);return found;}
    private static String websiteBranchMembership(Draft d,int id){List<Branch> found=branchesForStation(d,id);if(found.isEmpty())return "";StringJoiner names=new StringJoiner(" to ");for(Branch b:found)names.add(b.name);return names.toString();}
    private static void addWebsiteStationReference(JsonArray out,Draft d,Branch current,int id){List<Branch> found=branchesForStation(d,id);if(found.size()<2){out.add(id);return;}Branch other=null;for(Branch candidate:found)if(candidate!=current){other=candidate;break;}if(other==null){out.add(id);return;}JsonArray reference=new JsonArray();reference.add(id);reference.add(other.name);out.add(reference);}
    private static void addBranchJson(JsonObject out,Draft d,Branch b,boolean splitRuns){if(!splitRuns||b.breaks.isEmpty()){out.add(b.name,branchJson(d,b,b.vertices,b.stationIds));if(!splitRuns){JsonObject saved=out.getAsJsonObject(b.name);if(!b.breaks.isEmpty()){JsonArray breaks=new JsonArray();b.breaks.forEach(breaks::add);saved.add("plannerBreaks",breaks);}if(!b.links.isEmpty()){JsonArray links=new JsonArray();for(Link link:b.links){JsonArray pair=new JsonArray();pair.add(pointJson(link.a));pair.add(pointJson(link.b));links.add(pair);}saved.add("plannerLinks",links);}}}else{List<Integer>cuts=new ArrayList<>(b.breaks);cuts.add(b.vertices.size());int from=0,run=1;for(int to:cuts){if(to>from){String name=run==1?b.name:b.name+" Line "+run;out.add(name,branchJson(d,b,b.vertices.subList(from,to),run==1?b.stationIds:List.of()));run++;}from=to;}}if(splitRuns)for(int i=0;i<b.links.size();i++){Link link=b.links.get(i);out.add(b.name+" Connection "+(i+1),branchJson(d,b,List.of(link.a,link.b),List.of()));}}
    private static JsonArray pointJson(Point p){JsonArray value=new JsonArray();value.add(p.x);value.add(p.z);return value;}
    private static JsonObject branchJson(Draft d,Branch b,List<Point>points,List<Integer>ids){JsonObject bo=new JsonObject();JsonArray vs=new JsonArray();for(Point p:points){JsonArray v=new JsonArray();v.add(p.x);v.add(p.z);vs.add(v);}JsonArray stations=new JsonArray();for(int id:ids)addWebsiteStationReference(stations,d,b,id);bo.add("vertices",vs);bo.add("stations",stations);return bo;}

    private static JsonObject libraryJson(){JsonObject root=new JsonObject();root.addProperty("activeDraft",draftIndex);JsonArray all=new JsonArray();for(Draft d:drafts){JsonObject o=websiteJson(d,false);o.addProperty("draftName",d.name);o.addProperty("activeBranch",d.branch);o.addProperty("showMarkerInfo",d.coordinateMode!=3&&d.coordinateMode!=4);o.addProperty("coordinateMode",d.coordinateMode);JsonObject plannerYs=new JsonObject();for(Branch b:d.branches)plannerYs.addProperty(b.name,b.y);o.add("plannerBranchYs",plannerYs);all.add(o);}root.add("drafts",all);return root;}
    private static void loadLibrary(){Path p=libraryPath();if(!Files.isRegularFile(p)){loadLegacy();return;}try{JsonObject root=JsonParser.parseString(Files.readString(p)).getAsJsonObject();for(JsonElement e:root.getAsJsonArray("drafts"))drafts.add(parseDraft(e.getAsJsonObject()));draftIndex=root.has("activeDraft")?root.get("activeDraft").getAsInt():0;}catch(Exception e){drafts.clear();}}
    private static void loadLegacy(){Path p=FabricLoader.getInstance().getConfigDir().resolve("townymapaddon-ice-highway-draft.json");if(!Files.isRegularFile(p))return;try{Draft d=parseDraft(JsonParser.parseString(Files.readString(p)).getAsJsonObject());d.name="Draft 1";drafts.add(d);}catch(Exception ignored){}}
    private static Draft parseDraft(JsonObject root){String name=root.has("draftName")?root.get("draftName").getAsString():"Draft";JsonObject lines=root.getAsJsonObject("lines");String companyName=lines.keySet().iterator().next();JsonObject company=lines.getAsJsonObject(companyName);String lineName=company.keySet().iterator().next();JsonObject route=company.getAsJsonObject(lineName);Draft d=new Draft(name);d.company=companyName;d.line=lineName;d.prefix=route.has("prefix")?route.get("prefix").getAsString():"";d.code=route.has("code")?route.get("code").getAsString():"";d.color=route.has("color")?route.get("color").getAsString():"ff55dd";d.showMarkerInfo=!root.has("showMarkerInfo")||root.get("showMarkerInfo").getAsBoolean();d.coordinateMode=root.has("coordinateMode")?Math.clamp(root.get("coordinateMode").getAsInt(),0,4):(d.showMarkerInfo?0:3);d.branches.clear();for(var entry:route.getAsJsonObject("branches").entrySet()){Branch b=new Branch(entry.getKey());JsonObject o=entry.getValue().getAsJsonObject();b.y=root.has("plannerBranchYs")&&root.getAsJsonObject("plannerBranchYs").has(entry.getKey())?root.getAsJsonObject("plannerBranchYs").get(entry.getKey()).getAsDouble():(route.has("y")?route.get("y").getAsDouble():64);for(JsonElement v:o.getAsJsonArray("vertices")){JsonArray a=v.getAsJsonArray();b.vertices.add(new Point(a.get(0).getAsDouble(),a.get(1).getAsDouble()));}for(JsonElement id:o.getAsJsonArray("stations"))b.stationIds.add(id.isJsonArray()?id.getAsJsonArray().get(0).getAsInt():id.getAsInt());if(o.has("plannerBreaks"))for(JsonElement at:o.getAsJsonArray("plannerBreaks")){int index=at.getAsInt();if(index>0&&index<b.vertices.size())b.breaks.add(index);}if(o.has("plannerLinks"))for(JsonElement linked:o.getAsJsonArray("plannerLinks")){JsonArray pair=linked.getAsJsonArray(),a=pair.get(0).getAsJsonArray(),c=pair.get(1).getAsJsonArray();b.links.add(new Link(new Point(a.get(0).getAsDouble(),a.get(1).getAsDouble()),new Point(c.get(0).getAsDouble(),c.get(1).getAsDouble())));}d.branches.add(b);}if(d.branches.isEmpty())d.branches.add(new Branch("Main"));for(JsonElement e:root.getAsJsonArray("stations")){JsonObject o=e.getAsJsonObject();d.stations.add(new Station(o.get("id").getAsInt(),o.get("name").getAsString(),o.has("type")?o.get("type").getAsString():"station",o.get("x").getAsDouble(),o.has("y1")?o.get("y1").getAsDouble():(route.has("y")?route.get("y").getAsDouble():64),o.get("z").getAsDouble()));}d.branch=Math.clamp(root.has("activeBranch")?root.get("activeBranch").getAsInt():0,0,d.branches.size()-1);return d;}
    private static Path libraryPath(){return FabricLoader.getInstance().getConfigDir().resolve("townymapaddon-ice-highway-drafts.json");}private static Path plannerRoot(){Minecraft mc=Minecraft.getInstance();Path game=mc==null?FabricLoader.getInstance().getGameDir():mc.gameDirectory.toPath();return game.resolve("townymapaddon").resolve("ice-highway-planner").toAbsolutePath();}private static Path exportPath(){return plannerRoot().resolve("json").resolve("townymapaddon-ice-highway-"+safe(draft().name)+".json");}private static String safe(String s){return s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9._-]+","-");}
    public static boolean imageExportPending(){return pendingImageExport;}private static void saveLibrary(){saveLibraryQuiet();notice("Saved "+draft().name);}private static void saveLibraryQuiet(){write(libraryPath(),libraryJson());}private static void export(){Path p=exportPath();write(p,websiteJson());copyPath(p);notice("JSON saved: "+p+" (path copied)");}private static void exportImage(){saveLibraryQuiet();pendingImageExport=true;imageExportStartedAt=System.currentTimeMillis();Path dir=imageExportDirectory();copyPath(dir);TownyMapMod.armMapScreenshot();notice("Image will be saved in "+dir+" (path copied)");}public static void imageExportFinished(){if(!pendingImageExport)return;Path source=newestPlannerScreenshot();if(source==null)return;Path dir=imageExportDirectory();try{Files.createDirectories(dir);Path target=dir.resolve(source.getFileName());Files.move(source,target);pendingImageExport=false;copyPath(target);notice("Image saved: "+target+" (path copied)");}catch(IOException ignored){}}private static Path screenshotDirectory(){Minecraft mc=Minecraft.getInstance();Path game=mc==null?FabricLoader.getInstance().getGameDir():mc.gameDirectory.toPath();return game.resolve("screenshots").toAbsolutePath();}private static Path imageExportDirectory(){return plannerRoot().resolve("images");}private static Path newestPlannerScreenshot(){Path dir=screenshotDirectory();try(var files=Files.list(dir)){return files.filter(Files::isRegularFile).filter(p->p.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".png")).filter(p->modified(p)>=imageExportStartedAt-500).max(Comparator.comparingLong(IceRoadPlannerOverlay::modified)).orElse(null);}catch(IOException e){return null;}}private static long modified(Path p){try{return Files.getLastModifiedTime(p).toMillis();}catch(IOException e){return 0;}}private static void copyPath(Path p){Minecraft mc=Minecraft.getInstance();if(mc!=null&&mc.keyboardHandler!=null)mc.keyboardHandler.setClipboard(p.toString());}private static void write(Path p,JsonObject json){try{Files.createDirectories(p.getParent());Files.writeString(p,GSON.toJson(json));}catch(IOException e){notice("Save failed: "+p.toAbsolutePath());}}
    private static int sx(double x,double c,double s,int w){return (int)Math.round(w/2.0+(x-c)*s);}private static int sy(double z,double c,double s,int h){return (int)Math.round(h/2.0+(z-c)*s);}static double blockCenter(double v){return Math.floor(v)+0.5;}private static String number(double v){return Long.toString((long)Math.floor(v));}private static void line(GuiGraphicsExtractor g,int x1,int y1,int x2,int y2,int color,int width){double dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy);if(len<1)return;var m=g.pose();m.pushMatrix();try{m.translate(x1,y1);m.rotate((float)Math.atan2(dy,dx));g.fill(0,-width/2,(int)Math.ceil(len)+1,(width+1)/2,color);}finally{m.popMatrix();}}private static void notice(String s){feedback=s;feedbackUntil=System.currentTimeMillis()+2_000;}
}











