package net.townymap.gui;

import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.text.Text;
import net.townymap.TownyMapConfig;
import net.townymap.ice.IceRoadNetwork;
import java.util.*;

/** Viewport-culled ice-highway renderer for the 1.21.11 DrawContext API. */
public final class IceRoadOverlay {
 private static IceRoadNetwork.Station selected; private static List<Hit> hits=List.of(),routeHits=List.of();
 private record Hit(IceRoadNetwork.Station station,double x,double y){} private IceRoadOverlay(){}
 public static void render(DrawContext g,double cx,double cz,double scale,int sw,int sh,TownyMapConfig cfg){
  if(!cfg.iceRoadOverlayEnabled||scale<=0)return; var n=IceRoadNetwork.get(); double l=cx-sw/2d/scale,r=cx+sw/2d/scale,t=cz-sh/2d/scale,b=cz+sh/2d/scale;
  for(var s:n.segments()){if(Math.max(s.x1(),s.x2())<l||Math.min(s.x1(),s.x2())>r||Math.max(s.z1(),s.z2())<t||Math.min(s.z1(),s.z2())>b)continue;line(g,sx(s.x1(),cx,scale,sw),sy(s.z1(),cz,scale,sh),sx(s.x2(),cx,scale,sw),sy(s.z2(),cz,scale,sh),s.color(),5);}
  List<Hit> visible=new ArrayList<>();for(var s:n.stations()){if(s==null||s.x()<l||s.x()>r||s.z()<t||s.z()>b||!visible(cfg,s))continue;int x=sx(s.x(),cx,scale,sw),y=sy(s.z(),cz,scale,sh);symbol(g,x,y,s.type(),access(cfg,s),s==selected);visible.add(new Hit(s,x,y));}hits=List.copyOf(visible);if(selected!=null)card(g,sw,sh,cfg,selected);
 }
 public static boolean renderSelectedRoute(DrawContext g,double cx,double cz,double scale,int sw,int sh,double spawnX,double spawnZ,double targetX,double targetZ,IceRoadNetwork.Trip trip,TownyMapConfig cfg){
  if(trip==null||trip.path().isEmpty()){routeHits=List.of();return false;} dashed(g,sx(spawnX,cx,scale,sw),sy(spawnZ,cz,scale,sh),sx(trip.entryX(),cx,scale,sw),sy(trip.entryZ(),cz,scale,sh));
  for(var s:trip.path()){int x1=sx(s.x1(),cx,scale,sw),y1=sy(s.z1(),cz,scale,sh),x2=sx(s.x2(),cx,scale,sw),y2=sy(s.z2(),cz,scale,sh);line(g,x1,y1,x2,y2,0xFF101010,5);line(g,x1,y1,x2,y2,s.color(),3);} dashed(g,sx(trip.exitX(),cx,scale,sw),sy(trip.exitZ(),cz,scale,sh),sx(targetX,cx,scale,sw),sy(targetZ,cz,scale,sh));
  var n=IceRoadNetwork.get();List<Hit> next=new ArrayList<>();for(int id:trip.stationIds())if(id>=0&&id<n.stations().size()){var s=n.stations().get(id);if(s!=null){int x=sx(s.x(),cx,scale,sw),y=sy(s.z(),cz,scale,sh);symbol(g,x,y,s.type(),access(cfg,s),s==selected);next.add(new Hit(s,x,y));}}endpoint(g,sx(trip.entryX(),cx,scale,sw),sy(trip.entryZ(),cz,scale,sh));endpoint(g,sx(trip.exitX(),cx,scale,sw),sy(trip.exitZ(),cz,scale,sh));routeHits=List.copyOf(next);if(selected!=null&&next.stream().anyMatch(h->h.station==selected))card(g,sw,sh,cfg,selected);return true;
 }
 private static int sx(double x,double c,double s,int w){return(int)Math.round(w/2d+(x-c)*s);}private static int sy(double z,double c,double s,int h){return(int)Math.round(h/2d+(z-c)*s);}
 private static void line(DrawContext g,int x1,int y1,int x2,int y2,int c,int w){double dx=x2-x1,dy=y2-y1;int len=(int)Math.ceil(Math.hypot(dx,dy));if(len<1)return;var m=g.getMatrices();m.pushMatrix();try{m.translate(x1,y1);m.rotate((float)Math.atan2(dy,dx));g.fill(0,-w/2,len+1,(w+1)/2,c);}finally{m.popMatrix();}}
 private static void dashed(DrawContext g,int x1,int y1,int x2,int y2){double dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy);int n=Math.min(160,Math.max(1,(int)Math.ceil(len/14)));for(int i=0;i<n;i+=2){double a=i/(double)n,b=Math.min(1,(i+1d)/n);line(g,(int)(x1+dx*a),(int)(y1+dy*a),(int)(x1+dx*b),(int)(y1+dy*b),0xFFFFFFFF,3);}}
 private static void endpoint(DrawContext g,int x,int y){g.fill(x-6,y-6,x+7,y+7,0xFFFFFFFF);g.fill(x-4,y-4,x+5,y+5,0xFF25C6E8);}
 private static void symbol(DrawContext g,int x,int y,String type,String a,boolean on){int c=on?0xFFFFFF55:"OBSTRUCTED".equals(a)?0xFFFF6666:"ACCESSIBLE".equals(a)?0xFF65DDB4:0xFFFFFFFF;if(type.startsWith("jct")){g.fill(x-6,y-6,x+6,y-3,c);g.fill(x-6,y+3,x+6,y+6,c);g.fill(x-6,y-3,x-3,y+3,c);g.fill(x+3,y-3,x+6,y+3,c);}else if(type.startsWith("elev")){int d=type.endsWith("ew")?1:-1;for(int i=-2;i<=2;i++)g.fill(x+i*3*d-1,y+i*3-1,x+i*3*d+2,y+i*3+2,c);}else for(int i=0;i<12;i++){double p=i*Math.PI/6,q=(i+1)*Math.PI/6;line(g,(int)(x+5*Math.cos(p)),(int)(y+5*Math.sin(p)),(int)(x+5*Math.cos(q)),(int)(y+5*Math.sin(q)),c,3);}}
 private static void card(DrawContext g,int sw,int sh,TownyMapConfig cfg,IceRoadNetwork.Station s){int x=Math.max(8,sw-312),y=Math.max(8,sh-104);var tr=MinecraftClient.getInstance().textRenderer;g.fill(x,y,x+300,y+92,0xF20A1419);g.drawText(tr,s.name(),x+8,y+7,-1,false);g.drawText(tr,Text.translatable("townymapaddon.ice_station.coords",Math.round(s.x()),Math.round(s.z()),typeName(s.type())),x+8,y+21,0xFFB9C5CB,false);String d=s.notes().isBlank()?String.join(" · ",s.lines()):s.notes();if(d.length()>52)d=d.substring(0,49)+"...";g.drawText(tr,d,x+8,y+35,0xFFDDE7ED,false);String[] k={"unknown","accessible","blocked"},v={"UNKNOWN","ACCESSIBLE","OBSTRUCTED"};for(int i=0;i<3;i++){int bx=x+8+i*95;boolean on=v[i].equals(access(cfg,s));g.fill(bx,y+57,bx+91,y+78,on?0xFF315E70:0xFF1B2931);g.drawCenteredTextWithShadow(tr,Text.translatable("townymapaddon.ice_station.status."+k[i]),bx+45,y+63,on?-1:0xFFB9C5CB);}}
 public static boolean click(double mx,double my,int sw,int sh,TownyMapConfig cfg){if(!cfg.iceRoadOverlayEnabled)return false;boolean card=selected!=null&&inCard(mx,my,sw,sh);if(selected!=null&&update(mx,my,sw,sh,cfg,selected))return true;Hit h=nearest(mx,my,hits,81);if(h!=null){selected=h.station;return true;}if(!card)selected=null;return card;}
 public static boolean clickSelectedRoute(double mx,double my,int sw,int sh,TownyMapConfig cfg){if(selected!=null&&update(mx,my,sw,sh,cfg,selected))return true;if(selected!=null&&inCard(mx,my,sw,sh))return true;Hit h=nearest(mx,my,routeHits,169);if(h==null)return false;selected=h.station;return true;}
 private static boolean inCard(double x,double y,int sw,int sh){int l=Math.max(8,sw-312),t=Math.max(8,sh-104);return x>=l&&x<l+300&&y>=t&&y<t+92;}private static boolean update(double mx,double my,int sw,int sh,TownyMapConfig c,IceRoadNetwork.Station s){int x=Math.max(8,sw-312),y=Math.max(8,sh-104);if(mx<x+8||mx>=x+293||my<y+57||my>=y+78)return false;int i=(int)((mx-x-8)/95);String key=IceRoadNetwork.reportKey(s.id()),v=i==1?"ACCESSIBLE":i==2?"OBSTRUCTED":"UNKNOWN";if(i==0)c.iceRoadStationReports.remove(key);else c.iceRoadStationReports.put(key,v);c.save();return true;}private static Hit nearest(double x,double y,List<Hit> hs,double max){Hit best=null;for(Hit h:hs){double d=(h.x-x)*(h.x-x)+(h.y-y)*(h.y-y);if(d<max){max=d;best=h;}}return best;}
 private static String access(TownyMapConfig c,IceRoadNetwork.Station s){return c.iceRoadStationReports.getOrDefault(IceRoadNetwork.reportKey(s.id()),"UNKNOWN");}private static boolean visible(TownyMapConfig c,IceRoadNetwork.Station s){String a=access(c,s);return c.iceRoadStationFilter==0||c.iceRoadStationFilter==1&&"ACCESSIBLE".equals(a)||c.iceRoadStationFilter==2&&"OBSTRUCTED".equals(a);}private static Text typeName(String t){String k=t.startsWith("semi")?"semi_station":t.startsWith("jct")?"junction":t.startsWith("inter")?"interchange":t.startsWith("elev")?"elevator":"station";return Text.translatable("townymapaddon.ice_station.type."+k);}
}
