package net.townymap.gui;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.network.chat.Component;
import net.townymap.TownyMapConfig;
import net.townymap.ice.IceRoadNetwork;

import java.util.*;

/** Colored ice-highway lines, station symbols and a clickable station card. */
public final class IceRoadOverlay {
    private static IceRoadNetwork.Station selected;private static List<Hit>hits=List.of(),routeHits=List.of();private record Hit(IceRoadNetwork.Station station,double x,double y){}
    private IceRoadOverlay(){}
    public static void render(GuiGraphicsExtractor g,double camX,double camZ,double scale,int sw,int sh,TownyMapConfig cfg){if(!cfg.iceRoadOverlayEnabled||scale<=0)return;IceRoadNetwork n=IceRoadNetwork.get();double left=camX-sw/2.0/scale,right=camX+sw/2.0/scale,top=camZ-sh/2.0/scale,bottom=camZ+sh/2.0/scale;for(var s:n.segments()){if(Math.max(s.x1(),s.x2())<left||Math.min(s.x1(),s.x2())>right||Math.max(s.z1(),s.z2())<top||Math.min(s.z1(),s.z2())>bottom)continue;line(g,sx(s.x1(),camX,scale,sw),sy(s.z1(),camZ,scale,sh),sx(s.x2(),camX,scale,sw),sy(s.z2(),camZ,scale,sh),s.color(),5);}List<Hit>visible=new ArrayList<>();for(var s:n.stations()){if(s==null||s.x()<left||s.x()>right||s.z()<top||s.z()>bottom||!visibleByFilter(cfg,s))continue;int x=sx(s.x(),camX,scale,sw),y=sy(s.z(),camZ,scale,sh);symbol(g,x,y,s.type(),access(cfg,s),s==selected);visible.add(new Hit(s,x,y));}hits=List.copyOf(visible);if(selected!=null)card(g,sw,sh,cfg,selected);}
    private static int sx(double x,double c,double s,int w){return (int)Math.round(w/2.0+(x-c)*s);}private static int sy(double z,double c,double s,int h){return (int)Math.round(h/2.0+(z-c)*s);}
    private static void line(GuiGraphicsExtractor g,int x1,int y1,int x2,int y2,int color,int width){double dx=x2-x1,dy=y2-y1;int length=(int)Math.ceil(Math.hypot(dx,dy));if(length<=0)return;var m=g.pose();m.pushMatrix();try{m.translate(x1,y1);m.rotate((float)Math.atan2(dy,dx));g.fill(0,-width/2,length+1,(width+1)/2,color);}finally{m.popMatrix();}}
    /** Draws only the selected teleport result's highway subsection, with walking connectors at each end. */
    public static boolean renderSelectedRoute(GuiGraphicsExtractor g,double camX,double camZ,double scale,int sw,int sh,double spawnX,double spawnZ,double targetX,double targetZ,IceRoadNetwork.Trip trip,TownyMapConfig cfg){
        if(trip==null||trip.path().isEmpty()){routeHits=List.of();return false;}
        dashed(g,sx(spawnX,camX,scale,sw),sy(spawnZ,camZ,scale,sh),sx(trip.entryX(),camX,scale,sw),sy(trip.entryZ(),camZ,scale,sh),0xFFFFFFFF);
        for(var s:trip.path()){int x1=sx(s.x1(),camX,scale,sw),y1=sy(s.z1(),camZ,scale,sh),x2=sx(s.x2(),camX,scale,sw),y2=sy(s.z2(),camZ,scale,sh);line(g,x1,y1,x2,y2,0xFF101010,5);line(g,x1,y1,x2,y2,s.color(),3);}
        dashed(g,sx(trip.exitX(),camX,scale,sw),sy(trip.exitZ(),camZ,scale,sh),sx(targetX,camX,scale,sw),sy(targetZ,camZ,scale,sh),0xFFFFFFFF);
        IceRoadNetwork network=IceRoadNetwork.get();List<Hit> next=new ArrayList<>(trip.stationIds().size());
        for(int id:trip.stationIds()){if(id<0||id>=network.stations().size())continue;IceRoadNetwork.Station station=network.stations().get(id);if(station==null)continue;int x=sx(station.x(),camX,scale,sw),y=sy(station.z(),camZ,scale,sh);symbol(g,x,y,station.type(),access(cfg,station),station==selected);next.add(new Hit(station,x,y));}
        int entryX=sx(trip.entryX(),camX,scale,sw),entryY=sy(trip.entryZ(),camZ,scale,sh),exitX=sx(trip.exitX(),camX,scale,sw),exitY=sy(trip.exitZ(),camZ,scale,sh);endpoint(g,entryX,entryY,0xFF25C6E8);endpoint(g,exitX,exitY,0xFF25C6E8);
        routeHits=List.copyOf(next);if(selected!=null&&next.stream().anyMatch(hit->hit.station==selected))card(g,sw,sh,cfg,selected);return true;
    }
    private static void dashed(GuiGraphicsExtractor g,int x1,int y1,int x2,int y2,int color){double dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy);if(len<1)return;int pieces=Math.min(160,Math.max(1,(int)Math.ceil(len/14)));for(int i=0;i<pieces;i+=2){double a=i/(double)pieces,b=Math.min(1,(i+1)/(double)pieces);line(g,(int)Math.round(x1+dx*a),(int)Math.round(y1+dy*a),(int)Math.round(x1+dx*b),(int)Math.round(y1+dy*b),color,3);}}
    private static void endpoint(GuiGraphicsExtractor g,int x,int y,int color){g.fill(x-6,y-6,x+7,y+7,0xFFFFFFFF);g.fill(x-4,y-4,x+5,y+5,color);}
    private static void symbol(GuiGraphicsExtractor g,int x,int y,String type,String access,boolean active){int edge=active?0xFFFFFF55:"OBSTRUCTED".equals(access)?0xFFFF6666:"ACCESSIBLE".equals(access)?0xFF65DDB4:0xFFFFFFFF;if(type.startsWith("jct")){hollowSquare(g,x,y,edge);}else if(type.startsWith("inter")){interchange(g,x,y,edge,type.endsWith("1"));}else if(type.startsWith("elev")){int d=type.endsWith("ew")?1:-1;for(int i=-2;i<=2;i++)g.fill(x+i*3*d-1,y+i*3-1,x+i*3*d+2,y+i*3+2,edge);}else if(type.startsWith("semi")){int orientation=Character.getNumericValue(type.charAt(type.length()-1));halfRing(g,x,y,edge,orientation);}else ring(g,x,y,edge,0,12);}
    private static void interchange(GuiGraphicsExtractor g,int x,int y,int c,boolean right){if(right){g.fill(x+3,y-6,x+6,y+6,c);g.fill(x,y-4,x+3,y-1,c);g.fill(x-3,y-6,x,y-1,c);}else{g.fill(x-6,y-6,x-3,y+6,c);g.fill(x-3,y-4,x,y-1,c);g.fill(x,y-6,x+3,y-1,c);}g.fill(x-6,y-1,x+6,y+2,c);g.fill(x-6,y+3,x+6,y+6,c);}
    private static void hollowSquare(GuiGraphicsExtractor g,int x,int y,int c){g.fill(x-6,y-6,x+6,y-3,c);g.fill(x-6,y+3,x+6,y+6,c);g.fill(x-6,y-3,x-3,y+3,c);g.fill(x+3,y-3,x+6,y+3,c);}
    private static void ring(GuiGraphicsExtractor g,int x,int y,int c,int start,int count){double step=Math.PI*2/12;for(int i=start;i<start+count;i++){double a=i*step,b=(i+1)*step;line(g,(int)Math.round(x+5*Math.cos(a)),(int)Math.round(y+5*Math.sin(a)),(int)Math.round(x+5*Math.cos(b)),(int)Math.round(y+5*Math.sin(b)),c,3);}}
    private static void halfRing(GuiGraphicsExtractor g,int x,int y,int c,int orientation){int start=switch(orientation){case 1->6;case 2->3;case 3->0;default->9;};ring(g,x,y,c,start,6);if(orientation==1||orientation==3)g.fill(x-6,y-1,x+7,y+2,c);else g.fill(x-1,y-6,x+2,y+7,c);}
    private static void card(GuiGraphicsExtractor g,int sw,int sh,TownyMapConfig cfg,IceRoadNetwork.Station s){int w=300,h=92,x=Math.max(8,sw-w-12),y=Math.max(8,sh-h-12);g.fill(x,y,x+w,y+h,0xF20A1419);g.text(Minecraft.getInstance().font,s.name(),x+8,y+7,0xFFFFFFFF,false);g.text(Minecraft.getInstance().font,Component.translatable("townymapaddon.ice_station.coords",Math.round(s.x()),Math.round(s.z()),typeName(s.type())),x+8,y+21,0xFFB9C5CB,false);String detail=s.notes().isBlank()?(s.lines().isEmpty()?Component.translatable("townymapaddon.ice_station.no_line_information").getString():String.join(" · ",s.lines().subList(0,Math.min(2,s.lines().size())))):s.notes();if(detail.length()>52)detail=detail.substring(0,49)+"...";g.text(Minecraft.getInstance().font,detail,x+8,y+35,0xFFDDE7ED,false);String[] keys={"unknown","accessible","blocked"};String[] values={"UNKNOWN","ACCESSIBLE","OBSTRUCTED"};for(int i=0;i<3;i++){int bx=x+8+i*95;boolean on=values[i].equals(access(cfg,s));g.fill(bx,y+57,bx+91,y+78,on?0xFF315E70:0xFF1B2931);g.centeredText(Minecraft.getInstance().font,Component.translatable("townymapaddon.ice_station.status."+keys[i]),bx+45,y+63,on?0xFFFFFFFF:0xFFB9C5CB);}}
    public static boolean click(double mx,double my,int sw,int sh,TownyMapConfig cfg){if(!cfg.iceRoadOverlayEnabled)return false;boolean insideCard=false;if(selected!=null){int x=Math.max(8,sw-312),y=Math.max(8,sh-104);insideCard=mx>=x&&mx<x+300&&my>=y&&my<y+92;if(mx>=x+8&&mx<x+293&&my>=y+57&&my<y+78){int i=(int)((mx-(x+8))/95);if(i>=0&&i<3){String[]v={"UNKNOWN","ACCESSIBLE","OBSTRUCTED"};String key=IceRoadNetwork.reportKey(selected.id());if(i==0)cfg.iceRoadStationReports.remove(key);else cfg.iceRoadStationReports.put(key,v[i]);cfg.save();return true;}}}Hit best=null;double bd=81;for(Hit h:hits){double d=(h.x-mx)*(h.x-mx)+(h.y-my)*(h.y-my);if(d<bd){bd=d;best=h;}}if(best!=null){selected=best.station;return true;}if(selected!=null&&!insideCard)selected=null;return insideCard;}
    public static boolean clickSelectedRoute(double mx,double my,int sw,int sh,TownyMapConfig cfg){if(routeHits.isEmpty())return false;if(selected!=null&&routeHits.stream().anyMatch(hit->hit.station==selected)){int x=Math.max(8,sw-312),y=Math.max(8,sh-104);if(mx>=x+8&&mx<x+293&&my>=y+57&&my<y+78){int i=(int)((mx-(x+8))/95);if(i>=0&&i<3){String[] values={"UNKNOWN","ACCESSIBLE","OBSTRUCTED"};String key=IceRoadNetwork.reportKey(selected.id());if(i==0)cfg.iceRoadStationReports.remove(key);else cfg.iceRoadStationReports.put(key,values[i]);cfg.save();return true;}}if(mx>=x&&mx<x+300&&my>=y&&my<y+92)return true;}Hit best=null;double bd=169;for(Hit hit:routeHits){double d=(hit.x-mx)*(hit.x-mx)+(hit.y-my)*(hit.y-my);if(d<bd){bd=d;best=hit;}}if(best==null)return false;selected=best.station;return true;}
    private static String access(TownyMapConfig cfg,IceRoadNetwork.Station s){return cfg.iceRoadStationReports.getOrDefault(IceRoadNetwork.reportKey(s.id()),"UNKNOWN");}private static Component typeName(String t){String key=t.startsWith("semi")?"semi_station":t.startsWith("jct")?"junction":t.startsWith("inter")?"interchange":t.startsWith("elev")?"elevator":"station";return Component.translatable("townymapaddon.ice_station.type."+key);}
    private static boolean visibleByFilter(TownyMapConfig cfg,IceRoadNetwork.Station s){String a=access(cfg,s);return cfg.iceRoadStationFilter==0||cfg.iceRoadStationFilter==1&&"ACCESSIBLE".equals(a)||cfg.iceRoadStationFilter==2&&"OBSTRUCTED".equals(a);}
}
