package net.townymap.gui;

import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.CommonComponents;
import net.minecraft.network.chat.Component;
import net.townymap.TownyMapMod;
import net.townymap.integration.XaeroWaypointBridge;
import net.townymap.teleport.*;
import java.util.*;

/** Scrollable route presentation; all route decisions remain in TeleportAccessService. */
public final class TeleportViewerScreen extends Screen{
    private final Screen parent;private final double targetX,targetZ;private boolean advanced,lastLoading=true;private int scroll;private String feedback="";private final Set<String> revealed=new HashSet<>();
    public TeleportViewerScreen(Screen parent,double x,double z){super(Component.translatable("townymapaddon.teleport.title"));this.parent=parent;targetX=x;targetZ=z;advanced=TownyMapMod.getConfig().teleportDefaultAdvanced;}
    @Override protected void init(){int left=Math.max(12,(width-Math.min(620,width-24))/2),right=width-left;addRenderableWidget(Button.builder(Component.translatable("townymapaddon.teleport.mode.standard"),b->{advanced=false;scroll=0;rebuildWidgets();}).bounds(left+12,72,120,22).build());addRenderableWidget(Button.builder(Component.translatable("townymapaddon.teleport.mode.advanced"),b->{advanced=true;scroll=0;rebuildWidgets();}).bounds(left+138,72,120,22).build());addRenderableWidget(Button.builder(Component.translatable("townymapaddon.teleport.target_waypoint"),b->{XaeroWaypointBridge.createTeleportWaypoint(Component.translatable("townymapaddon.teleport.target").getString(),(int)Math.round(targetX),0,(int)Math.round(targetZ));feedback=Component.translatable("townymapaddon.teleport.waypoint_created").getString();}).bounds(right-176,42,164,22).build());
        var plan=TownyMapMod.teleportPlan(targetX,targetZ);List<TeleportRoute> routes=advanced?plan.advanced():plan.standard();int top=132,row=82;for(int i=0;i<routes.size();i++){TeleportRoute r=routes.get(i);int y=top+i*row-scroll;if(y<top||y+row>height-42)continue;boolean risky=advanced&&r.membershipRisk().ordinal()>=TeleportRoute.MembershipRisk.HIGH.ordinal()&&!revealed.contains(routeKey(r));if(risky)addRenderableWidget(Button.builder(Component.translatable("townymapaddon.teleport.show_risky"),b->{revealed.add(routeKey(r));rebuildWidgets();}).bounds(right-150,y+51,138,22).build());else{Button copy=Button.builder(Component.translatable("townymapaddon.teleport.copy"),b->copy(r)).bounds(right-220,y+51,62,22).build();copy.active=r.destination().command()!=null&&!r.destination().command().isBlank();addRenderableWidget(copy);Button waypoint=Button.builder(Component.translatable("townymapaddon.teleport.waypoint"),b->waypoint(r)).bounds(right-154,y+51,72,22).build();waypoint.active=r.destination().x()!=0||r.destination().z()!=0;addRenderableWidget(waypoint);addRenderableWidget(Button.builder(Component.translatable("townymapaddon.teleport.report_spawn"),b->{TownyMapMod.cycleTeleportSpawnReport(r.destination());rebuildWidgets();}).bounds(right-78,y+51,66,22).build());}}addRenderableWidget(Button.builder(CommonComponents.GUI_DONE,b->onClose()).bounds(right-92,height-30,80,20).build());}
    private void copy(TeleportRoute r){String text=r.steps().stream().map(TeleportRoute.Step::command).filter(s->s!=null&&!s.isBlank()).reduce((a,b)->a+"\n"+b).orElse(r.destination().command());minecraft.keyboardHandler.setClipboard(text);feedback=Component.translatable("townymapaddon.teleport.copied",text.replace('\n',' ')).getString();}
    private void waypoint(TeleportRoute r){var d=r.destination();XaeroWaypointBridge.createTeleportWaypoint((d.type()==TeleportDestination.Type.TOWN_SPAWN?"TP ":"N Spawn ")+d.name(),d.x(),d.y(),d.z());feedback=Component.translatable("townymapaddon.teleport.waypoint_created").getString();}
    @Override public void tick(){super.tick();boolean loading=TownyMapMod.teleportPlan(targetX,targetZ).loading();if(lastLoading&&!loading)rebuildWidgets();lastLoading=loading;}
    @Override public boolean mouseScrolled(double x,double y,double h,double v){var p=TownyMapMod.teleportPlan(targetX,targetZ);int n=(advanced?p.advanced():p.standard()).size();scroll=Math.clamp(scroll-(int)Math.round(v*40),0,Math.max(0,n*82-(height-174)));rebuildWidgets();return true;}
    @Override public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float d){int left=Math.max(12,(width-Math.min(620,width-24))/2),right=width-left;g.fill(left-2,16,right+2,height-8,0xEE080B0E);g.fill(left,18,right,height-10,0xF015191D);super.extractRenderState(g,mx,my,d);g.centeredText(font,title,width/2,25,0xFFFFFFFF);g.text(font,Component.translatable("townymapaddon.teleport.target_context",TownyMapMod.teleportTargetContext(targetX,targetZ)),left+12,47,0xFFB9C3CC,false);if(!feedback.isBlank())g.text(font,feedback,left+12,103,0xFF7EE2B8,false);var plan=TownyMapMod.teleportPlan(targetX,targetZ);if(plan.loading()){g.centeredText(font,Component.translatable("townymapaddon.teleport.loading"),width/2,120,0xFFFFFF88);return;}if(advanced&&plan.player()!=null){int color=plan.player().isMayor()?0xFFFF5555:0xFFFFAA55;g.text(font,Component.translatable(plan.player().isMayor()?"townymapaddon.teleport.warning.mayor":"townymapaddon.teleport.warning.advanced",plan.player().town()),left+12,106,color,false);}List<TeleportRoute> routes=advanced?plan.advanced():plan.standard();if(routes.isEmpty()){g.centeredText(font,Component.translatable("townymapaddon.teleport.none"),width/2,145,0xFFFFAA55);return;}int top=132,row=82;for(int i=0;i<routes.size();i++){TeleportRoute r=routes.get(i);int y=top+i*row-scroll;if(y<top||y+row>height-42)continue;g.fill(left+10,y,right-10,y+76,0xE0122B20);g.text(font,r.destination().name(),left+18,y+9,0xFFFFFFFF,false);g.text(font,Component.translatable("townymapaddon.teleport.blocks",(int)Math.round(r.walkingDistance())),right-105,y+9,0xFFFFFFFF,false);g.text(font,r.destination().command(),left+18,y+25,0xFF9BFFD3,false);g.text(font,Component.translatable("townymapaddon.teleport.eligibility_reason."+r.destination().reason().name().toLowerCase(Locale.ROOT)),left+18,y+39,0xFFB8C0C7,false);g.text(font,Component.translatable("townymapaddon.teleport.spawn_status",r.destination().physicalAccess()),left+270,y+39,r.destination().physicalAccess()==TeleportDestination.PhysicalAccess.OBSTRUCTED?0xFFFF7777:0xFFFFCC77,false);if(advanced&&r.saving()!=0)g.text(font,Component.translatable("townymapaddon.teleport.saving",(int)Math.round(r.saving())),left+18,y+64,r.saving()>0?0xFF8FE3A8:0xFFFFAA55,false);}}
    private static String routeKey(TeleportRoute r){return r.mode()+":"+r.destination().type()+":"+r.destination().name();}@Override public void onClose(){minecraft.gui.setScreen(parent);}
}
