package net.townymap.hunter.front;

import net.townymap.TownyMapConfig;
import net.townymap.hunter.model.*;
import java.util.*;

/** Owns hidden sessions, origins, front crossings and authoritative render geometry. */
public final class HiddenThreatFrontEngine {
    private final TownyMapConfig config;private final Map<String,Session> sessions=new HashMap<>();private volatile List<Front> fronts=List.of();
    public HiddenThreatFrontEngine(TownyMapConfig config){this.config=config;}
    public Update update(HunterState actor,long now,double playerX,double playerZ,List<ApproachRoute> routes){return update(actor,now,playerX,playerZ,routes,null,null,null);}
    public Update update(HunterState actor,long now,double playerX,double playerZ,List<ApproachRoute> routes,Double escapeX,Double escapeZ,String escapeDestination,boolean teleportOriginsActive){if(teleportOriginsActive&&actor.teleportFrontActivatedAtMs==0)actor.teleportFrontActivatedAtMs=now;if(!teleportOriginsActive)actor.teleportFrontActivatedAtMs=0;Update result=update(actor,now,playerX,playerZ,teleportOriginsActive?routes:List.of(),escapeX,escapeZ,escapeDestination);Session session=sessions.get(key(actor.name));if(session!=null){session.latentRoutes=routes==null?List.of():List.copyOf(routes);if(!teleportOriginsActive)session.teleportStats=new TeleportStats(session.latentRoutes.size(),0,0,session.teleportStats.indexRebuilds(),session.teleportStats.reranks());}return result;}
    public Update update(HunterState actor,long now,double playerX,double playerZ,List<ApproachRoute> routes,Double escapeX,Double escapeZ,String escapeDestination){String hunterKey=key(actor.name);if(!config.hunterThreatFrontsEnabled||actor.visibility!=HunterState.Visibility.HIDDEN||actor.online==HunterState.OnlineStatus.OFFLINE){boolean removed=sessions.remove(hunterKey)!=null;if(removed)publish(now,playerX,playerZ);return Update.empty();}Session session=sessions.computeIfAbsent(hunterKey,k->new Session(actor.hiddenSinceMs,selector()));var selection=session.selector.select(routes,playerX,playerZ,escapeX,escapeZ,escapeDestination,actor.source==HunterState.Source.MANUAL_HUNTER,now);session.teleportStats=new TeleportStats(selection.latentCount(),selection.relevantClusterCount(),selection.relevantRepresentatives().size(),selection.indexRebuilds(),selection.reranks());Map<String,HiddenThreatOrigin>wanted=origins(actor,hunterKey,selection.relevantRepresentatives());session.origins.keySet().retainAll(wanted.keySet());wanted.forEach(session.origins::putIfAbsent);ArrayList<Crossing>crossings=new ArrayList<>();int warningInside=0,plausibleInside=0;Front nearest=null;double nearestEdge=Double.POSITIVE_INFINITY;for(var origin:session.origins.values()){var radii=ThreatFrontCalculator.calculate(origin,now,config.hunterFrontPlausibleSpeed,config.hunterFrontWarningSpeed,config.hunterFrontWarningLeadSeconds*1000L,config.hunterFrontTeleportSafetyMargin);double distance=Math.hypot(origin.x()-playerX,origin.z()-playerZ);CrossState state=session.crossings.computeIfAbsent(origin.key(),k->new CrossState());boolean warning=transition(state.warningInside,distance,radii.warning(),config.hunterFrontReentryHysteresis);boolean plausible=transition(state.plausibleInside,distance,radii.plausible(),config.hunterFrontReentryHysteresis);if(warning&&!state.warningInside&&eligible(actor,false)&&now-state.lastWarningAt>=15_000){crossings.add(new Crossing(origin,FrontType.WARNING,distance,radii.warning()));state.lastWarningAt=now;}if(plausible&&!state.plausibleInside&&eligible(actor,true)&&now-state.lastPlausibleAt>=15_000){crossings.add(new Crossing(origin,FrontType.PLAUSIBLE,distance,radii.plausible()));state.lastPlausibleAt=now;}state.warningInside=warning;state.plausibleInside=plausible;if(warning)warningInside++;if(plausible)plausibleInside++;double edge=distance-radii.warning();if(edge<nearestEdge){nearestEdge=edge;nearest=new Front(origin,radii.plausible(),radii.warning(),distance,warning,plausible,relevance(origin,distance,radii,warning,plausible),now);}}
        if(config.hunterAggregateTeleportWarnings){AggregateSeverity current=plausibleInside>0?AggregateSeverity.PLAUSIBLE_RANGE:warningInside>0?AggregateSeverity.WARNING_RANGE:AggregateSeverity.CLEAR;if(current.ordinal()>session.aggregate.ordinal()){FrontType wantedType=current==AggregateSeverity.PLAUSIBLE_RANGE?FrontType.PLAUSIBLE:FrontType.WARNING;Crossing best=crossings.stream().filter(c->c.type==wantedType).min(Comparator.comparingDouble(Crossing::playerDistance)).orElse(null);crossings.clear();if(best!=null)crossings.add(best);}else crossings.clear();session.aggregate=current;}
        publish(now,playerX,playerZ);return new Update(List.copyOf(crossings),new Summary(warningInside,plausibleInside,session.origins.size(),nearest,nearestEdge));}
    public void remove(String hunterName){if(sessions.remove(key(hunterName))!=null)rebuildFronts(System.currentTimeMillis(),0,0);}
    public void clear(){sessions.clear();fronts=List.of();}
    public void retainActors(Collection<HunterState> actors,long now,double playerX,double playerZ){Set<String> active=new HashSet<>();for(HunterState actor:actors)active.add(key(actor.name));if(sessions.keySet().retainAll(active))rebuildFronts(now,playerX,playerZ);}
    public List<Front> allFronts(){return fronts;}
    public TeleportStats teleportStats(String hunterName){Session s=sessions.get(key(hunterName));return s==null?TeleportStats.empty():s.teleportStats;}
    public List<LatentTeleport> latentTeleports(int limit){int cap=Math.max(0,limit);if(cap==0)return List.of();ArrayList<LatentTeleport> out=new ArrayList<>();outer:for(var entry:sessions.entrySet())for(ApproachRoute route:entry.getValue().latentRoutes){out.add(new LatentTeleport(entry.getKey(),route.name(),route.type(),route.x(),route.z()));if(out.size()>=cap)break outer;}return List.copyOf(out);}
    public List<Front> renderFronts(int limit){int cap=Math.max(0,limit);if(cap==0)return List.of();List<Front> ranked=fronts.stream().sorted(Comparator.comparingDouble(Front::relevance).reversed()).toList();LinkedHashMap<String,Front> selected=new LinkedHashMap<>();int teleportReserve=Math.min(Math.max(1,cap/2),cap);ranked.stream().filter(f->(f.playerInsideWarning||f.playerInsidePlausible)&&!isTeleport(f.origin.type())).limit(cap-teleportReserve).forEach(f->selected.put(f.origin.key(),f));ranked.stream().filter(f->isTeleport(f.origin.type())).limit(teleportReserve).forEach(f->{if(selected.size()<cap)selected.putIfAbsent(f.origin.key(),f);});for(Front f:ranked){if(selected.size()>=cap)break;selected.putIfAbsent(f.origin.key(),f);}return List.copyOf(selected.values());}
    public List<Front> renderFronts(int globalLimit,int perHunterTeleportLimit){int cap=Math.max(0,globalLimit),perHunter=Math.max(0,perHunterTeleportLimit);if(cap==0)return List.of();List<Front> ranked=fronts.stream().sorted(Comparator.comparingDouble(Front::relevance).reversed()).toList();ArrayList<Front> selected=new ArrayList<>();Map<String,Integer> teleportCounts=new HashMap<>();for(Front front:ranked){if(selected.size()>=cap)break;if(isTeleport(front.origin.type())){int count=teleportCounts.getOrDefault(front.origin.hunterKey(),0);if(count>=perHunter)continue;teleportCounts.put(front.origin.hunterKey(),count+1);}selected.add(front);}return List.copyOf(selected);}
    public int routeIntersectionCount(double x1,double z1,double x2,double z2,long now){int n=0;for(Front f:fronts){var r=ThreatFrontCalculator.calculate(f.origin,now,config.hunterFrontPlausibleSpeed,config.hunterFrontWarningSpeed,config.hunterFrontWarningLeadSeconds*1000L,config.hunterFrontTeleportSafetyMargin);if(segmentDistance(x1,z1,x2,z2,f.origin.x(),f.origin.z())<=r.warning())n++;}return n;}
    private boolean eligible(HunterState actor,boolean plausible){if(plausible&&!config.hunterPlausibleFrontCrossingAlert||!plausible&&!config.hunterWarningFrontCrossingAlert)return false;if(actor.source==HunterState.Source.MANUAL_HUNTER)return config.hunterKnownFrontWarnings;return config.hunterPotentialFrontWarnings;}
    private Map<String,HiddenThreatOrigin> origins(HunterState actor,String hunterKey,List<ApproachRoute> routes){Map<String,HiddenThreatOrigin> out=new LinkedHashMap<>();HunterState.Observation last=actor.direct!=null?actor.direct:actor.lastSeen;if(last!=null){var o=new HiddenThreatOrigin(hunterKey,actor.name,actor.source==HunterState.Source.MANUAL_HUNTER,HiddenThreatOrigin.Type.LAST_KNOWN_POSITION,"last","Last known",last.x(),last.z(),actor.hiddenSinceMs,actor.hiddenSinceMs,32,false);out.put(o.key(),o);}HunterState.Observation combat=actor.inferred;boolean combatLinkedToSession=combat!=null&&(combat.atMs()>=actor.hiddenSinceMs||last!=null&&Math.abs(combat.atMs()-last.atMs())<=config.hunterKillOriginFreshnessSeconds*1000L);if(combatLinkedToSession&&combat.type()==HunterState.ObservationType.COMBAT_INFERRED){var o=new HiddenThreatOrigin(hunterKey,actor.name,actor.source==HunterState.Source.MANUAL_HUNTER,HiddenThreatOrigin.Type.KILL_EVENT_ORIGIN,"combat:"+combat.atMs(),"Kill event",combat.x(),combat.z(),combat.atMs(),combat.atMs(),12,false);out.put(o.key(),o);}long activation=actor.teleportFrontActivatedAtMs>0?actor.teleportFrontActivatedAtMs:actor.hiddenSinceMs;long teleportStart=activation+Math.max(0,config.hunterFrontTeleportDelaySeconds)*1000L;for(ApproachRoute route:routes){HiddenThreatOrigin.Type type=route.type()==ApproachRoute.Type.TOWN?HiddenThreatOrigin.Type.TOWN_SPAWN:HiddenThreatOrigin.Type.NATION_SPAWN;var o=new HiddenThreatOrigin(hunterKey,actor.name,actor.source==HunterState.Source.MANUAL_HUNTER,type,route.key(),route.name(),route.x(),route.z(),activation,teleportStart,config.hunterTeleportActivationInitialRadius,route.recentEntryMatch());out.put(o.key(),o);}return out;}
    private void publish(long now,double px,double pz){rebuildFronts(now,px,pz);}
    private void rebuildFronts(long now,double px,double pz){ArrayList<Front> out=new ArrayList<>();for(Session s:sessions.values())for(HiddenThreatOrigin o:s.origins.values()){var r=ThreatFrontCalculator.calculate(o,now,config.hunterFrontPlausibleSpeed,config.hunterFrontWarningSpeed,config.hunterFrontWarningLeadSeconds*1000L,config.hunterFrontTeleportSafetyMargin);double d=Math.hypot(o.x()-px,o.z()-pz);CrossState c=s.crossings.get(o.key());boolean wi=c!=null&&c.warningInside,pi=c!=null&&c.plausibleInside;out.add(new Front(o,r.plausible(),r.warning(),d,wi,pi,relevance(o,d,r,wi,pi),now));}fronts=List.copyOf(out);}
    private static boolean transition(boolean inside,double distance,double radius,double hysteresis){return inside?distance<=radius+Math.max(0,hysteresis):distance<=radius;}
    private static boolean isTeleport(HiddenThreatOrigin.Type type){return type==HiddenThreatOrigin.Type.TOWN_SPAWN||type==HiddenThreatOrigin.Type.NATION_SPAWN||type==HiddenThreatOrigin.Type.OTHER_TELEPORT;}
    private static double relevance(HiddenThreatOrigin o,double d,ThreatFrontCalculator.Radii r,boolean warning,boolean plausible){return(plausible?1_000_000:warning?500_000:0)-Math.max(0,d-r.warning())+(o.type()==HiddenThreatOrigin.Type.KILL_EVENT_ORIGIN?100_000:o.type()==HiddenThreatOrigin.Type.LAST_KNOWN_POSITION?50_000:0)+(o.recentEntry()?25_000:0);}
    static double segmentDistance(double x1,double y1,double x2,double y2,double px,double py){double dx=x2-x1,dy=y2-y1;if(dx==0&&dy==0)return Math.hypot(px-x1,py-y1);double t=Math.clamp(((px-x1)*dx+(py-y1)*dy)/(dx*dx+dy*dy),0,1);return Math.hypot(px-(x1+t*dx),py-(y1+t*dy));}
    private static String key(String s){return s==null?"":s.toLowerCase(Locale.ROOT);}
    private TeleportThreatSelector selector(){return new TeleportThreatSelector(config.hunterTeleportThreatSpatialRadius,config.hunterTeleportThreatClusterRadius,config.hunterMaxRelevantTeleportThreats,config.hunterTeleportThreatRerankMovement,config.hunterTeleportThreatRerankSeconds*1000L,config.hunterTeleportThreatPromotionHysteresisPercent/100.0,config.hunterTeleportThreatDemotionHysteresisPercent/100.0);}
    private static final class Session{final long startedAt;final TeleportThreatSelector selector;List<ApproachRoute>latentRoutes=List.of();final Map<String,HiddenThreatOrigin>origins=new LinkedHashMap<>();final Map<String,CrossState>crossings=new HashMap<>();AggregateSeverity aggregate=AggregateSeverity.CLEAR;TeleportStats teleportStats=TeleportStats.empty();Session(long at,TeleportThreatSelector selector){startedAt=at;this.selector=selector;}}
    private static final class CrossState{boolean warningInside,plausibleInside;long lastWarningAt=Long.MIN_VALUE/2,lastPlausibleAt=Long.MIN_VALUE/2;}
    public enum FrontType{WARNING,PLAUSIBLE}
    public enum AggregateSeverity{CLEAR,WARNING_RANGE,PLAUSIBLE_RANGE}
    public record Crossing(HiddenThreatOrigin origin,FrontType type,double playerDistance,double radius){}
    public record Front(HiddenThreatOrigin origin,double plausibleRadius,double warningRadius,double playerDistance,boolean playerInsideWarning,boolean playerInsidePlausible,double relevance,long calculatedAt){}
    public record Summary(int warningContainingPlayer,int plausibleContainingPlayer,int originCount,Front nearest,double distanceToWarningFront){public static Summary empty(){return new Summary(0,0,0,null,Double.POSITIVE_INFINITY);}}
    public record Update(List<Crossing> crossings,Summary summary){static Update empty(){return new Update(List.of(),Summary.empty());}}
    public record TeleportStats(int latentOrigins,int relevantClusters,int activeLogicalOrigins,int indexRebuilds,int reranks){static TeleportStats empty(){return new TeleportStats(0,0,0,0,0);}}
    public record LatentTeleport(String hunterKey,String name,ApproachRoute.Type type,double x,double z){}
}
