package net.townymap.hunter.front;

import net.townymap.hunter.model.ApproachRoute;
import java.util.*;

/** Cached spatial index, clustering and stable ranking for a hunter's complete teleport network. */
public final class TeleportThreatSelector {
    private final double searchRadius,clusterRadius,moveThreshold,promotionHysteresis,demotionHysteresis;private final int maxRelevant;private final long rerankIntervalMs;
    private Map<Long,List<ApproachRoute>> grid=Map.of();private List<ApproachRoute> all=List.of(),selected=List.of();private long signature,lastRankAt;private double lastX=Double.NaN,lastZ=Double.NaN;private int rebuilds,reranks,lastRelevantClusterCount;
    public TeleportThreatSelector(double searchRadius,double clusterRadius,int maxRelevant,double moveThreshold,long rerankIntervalMs,double promotionHysteresis,double demotionHysteresis){this.searchRadius=Math.max(500,searchRadius);this.clusterRadius=Math.max(32,clusterRadius);this.maxRelevant=Math.max(1,maxRelevant);this.moveThreshold=Math.max(16,moveThreshold);this.rerankIntervalMs=Math.max(250,rerankIntervalMs);this.promotionHysteresis=Math.max(0,promotionHysteresis);this.demotionHysteresis=Math.max(0,demotionHysteresis);}
    public Selection select(List<ApproachRoute> routes,double px,double pz,Double escapeX,Double escapeZ,String escapeDestination,boolean known,long now){long nextSignature=signature(routes);if(nextSignature!=signature){signature=nextSignature;all=routes==null?List.of():List.copyOf(routes);rebuild();lastRankAt=0;}boolean moved=!Double.isFinite(lastX)||Math.hypot(px-lastX,pz-lastZ)>=moveThreshold;if(!moved&&now-lastRankAt<rerankIntervalMs)return snapshot();lastX=px;lastZ=pz;lastRankAt=now;reranks++;
        List<Scored> scored=new ArrayList<>();for(Cluster cluster:clusters(query(px,pz))){ApproachRoute best=null;double bestScore=-1;String reason="proximity";for(ApproachRoute route:cluster.members){double d=Math.hypot(route.x()-px,route.z()-pz),score=Math.max(0,1-d/searchRadius)*.55;boolean intersects=escapeX!=null&&escapeZ!=null&&segmentDistance(px,pz,escapeX,escapeZ,route.x(),route.z())<=clusterRadius;boolean shared=escapeDestination!=null&&!escapeDestination.isBlank()&&route.name().equalsIgnoreCase(escapeDestination);if(intersects)score+=.25;if(shared)score+=.35;double hunterArrival=8+d/8.0,playerArrival=escapeX==null?Double.POSITIVE_INFINITY:Math.hypot(escapeX-px,escapeZ-pz)/5.6;if(hunterArrival<=playerArrival)score+=.15;if(known)score+=.05;String candidateReason=shared?"shared teleport spawn":intersects?"escape-route intersection":hunterArrival<=playerArrival?"earliest interception":"proximity";if(score>bestScore){bestScore=score;best=route;reason=candidateReason;}}if(best!=null)scored.add(new Scored(best,List.copyOf(cluster.members),bestScore,reason));}
        scored.sort(Comparator.comparingDouble(Scored::score).reversed().thenComparing(s->s.representative.key()));List<ApproachRoute> previous=selected;ArrayList<ApproachRoute> next=new ArrayList<>();for(Scored candidate:scored){if(next.size()>=maxRelevant)break;boolean wasActive=previous.stream().anyMatch(r->r.key().equals(candidate.representative.key()));double cutoff=scored.size()>maxRelevant?scored.get(maxRelevant).score:0;if(wasActive||candidate.score>=cutoff+promotionHysteresis)next.add(candidate.representative);}
        for(ApproachRoute old:previous){if(next.size()>=maxRelevant)break;if(next.stream().noneMatch(r->r.key().equals(old.key()))){double oldScore=scored.stream().filter(s->s.representative.key().equals(old.key())).mapToDouble(Scored::score).findFirst().orElse(-1);double floor=scored.isEmpty()?0:scored.get(Math.min(maxRelevant-1,scored.size()-1)).score;if(oldScore+demotionHysteresis>=floor)next.add(old);}}
        selected=List.copyOf(next);lastRelevantClusterCount=scored.size();return new Selection(all.size(),lastRelevantClusterCount,selected,scored.stream().limit(maxRelevant).toList(),rebuilds,reranks);}
    private Selection snapshot(){return new Selection(all.size(),lastRelevantClusterCount,selected,List.of(),rebuilds,reranks);}
    public List<ApproachRoute> latentSnapshot(){return all;}
    private void rebuild(){rebuilds++;Map<Long,List<ApproachRoute>> mutable=new HashMap<>();for(ApproachRoute r:all)mutable.computeIfAbsent(gridCell(r.x(),r.z()),ignored->new ArrayList<>()).add(r);Map<Long,List<ApproachRoute>> frozen=new HashMap<>();mutable.forEach((k,v)->frozen.put(k,List.copyOf(v)));grid=Map.copyOf(frozen);}
    private List<ApproachRoute> query(double x,double z){int minX=(int)Math.floor((x-searchRadius)/searchRadius),maxX=(int)Math.floor((x+searchRadius)/searchRadius),minZ=(int)Math.floor((z-searchRadius)/searchRadius),maxZ=(int)Math.floor((z+searchRadius)/searchRadius);ArrayList<ApproachRoute> out=new ArrayList<>();for(int gx=minX;gx<=maxX;gx++)for(int gz=minZ;gz<=maxZ;gz++)for(ApproachRoute r:grid.getOrDefault(cellKey(gx,gz),List.of()))if(Math.hypot(r.x()-x,r.z()-z)<=searchRadius)out.add(r);return out;}
    private List<Cluster> clusters(List<ApproachRoute> routes){ArrayList<Cluster> clusters=new ArrayList<>();for(ApproachRoute route:routes.stream().sorted(Comparator.comparing(ApproachRoute::key)).toList()){Cluster target=null;for(Cluster c:clusters)if(c.members.stream().anyMatch(r->Math.hypot(r.x()-route.x(),r.z()-route.z())<=clusterRadius)){target=c;break;}if(target==null){target=new Cluster();clusters.add(target);}target.members.add(route);}return clusters;}
    private long gridCell(double x,double z){return cellKey((int)Math.floor(x/searchRadius),(int)Math.floor(z/searchRadius));}private static long cellKey(int x,int z){return((long)x<<32)^(z&0xffffffffL);}
    private static long signature(List<ApproachRoute> routes){long h=1125899906842597L;if(routes!=null)for(ApproachRoute r:routes)h=31*h+Objects.hash(r.key(),r.x(),r.z());return h;}
    static double segmentDistance(double x1,double y1,double x2,double y2,double px,double py){double dx=x2-x1,dy=y2-y1;if(dx==0&&dy==0)return Math.hypot(px-x1,py-y1);double t=Math.clamp(((px-x1)*dx+(py-y1)*dy)/(dx*dx+dy*dy),0,1);return Math.hypot(px-(x1+t*dx),py-(y1+t*dy));}
    private static final class Cluster{final List<ApproachRoute> members=new ArrayList<>();}
    public record Scored(ApproachRoute representative,List<ApproachRoute> members,double score,String reason){}
    public record Selection(int latentCount,int relevantClusterCount,List<ApproachRoute> relevantRepresentatives,List<Scored> ranked,int indexRebuilds,int reranks){}
}
