$ErrorActionPreference = 'Stop'
$base = if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) { (Get-Location).Path } else { Join-Path $PSScriptRoot '..' }
$root = Join-Path $base 'src/main/resources/assets/townymapaddon/lang'
$maps = @{
  'zh_cn' = @{
    'townymapaddon.hunter.activity.title'='猎人动态'; 'townymapaddon.hunter.chat.warning_prefix'='[猎人警报] [警告]'; 'townymapaddon.hunter.chat.notification_prefix'='[猎人警报]'; 'townymapaddon.hunter.hud.possible_hunter'='疑似猎人'; 'townymapaddon.hunter.hud.warning'='警告'; 'townymapaddon.hunter.hud.recent_event'='最近事件'; 'townymapaddon.hunter.candidate.outlaw_count'='被 %1$s 个城镇通缉'; 'townymapaddon.hunter.hud.tracked'='%1$s · %2$s米 %3$s'; 'townymapaddon.hunter.hud.visible_claim'='可见 · %1$s'; 'townymapaddon.hunter.hud.lost_claim'='失联 %1$s · %2$s'; 'townymapaddon.hunter.hud.risk_score'='风险 %1$s %2$s'; 'townymapaddon.hunter.hud.tp_threat'='传送威胁 ~%1$s米 · %2$s'; 'townymapaddon.hunter.hud.more'='另有 %1$s 人';
    'townymapaddon.teleport.title'='传送路线查看器'; 'townymapaddon.teleport.find_here'='查找前往此处的传送点'; 'townymapaddon.teleport.mode.standard'='标准'; 'townymapaddon.teleport.mode.advanced'='高级'; 'townymapaddon.teleport.target'='目标'; 'townymapaddon.teleport.target_context'='目标：%1$s'; 'townymapaddon.teleport.target_waypoint'='目标航点'; 'townymapaddon.teleport.arrival_waypoint'='抵达航点'; 'townymapaddon.teleport.waypoint_created'='已创建航点'; 'townymapaddon.teleport.blocks'='%1$s 格'; 'townymapaddon.teleport.loading'='正在加载传送路线…'; 'townymapaddon.teleport.none'='未找到可用的传送路线。'; 'townymapaddon.teleport.wilderness'='荒野'; 'townymapaddon.teleport.clear_results'='清除结果'; 'townymapaddon.teleport.results_cleared'='结果和地图路线已清除。双击新地点再次搜索。'; 'townymapaddon.teleport.destination_coords'='目的地：X %1$s，Z %2$s'; 'townymapaddon.teleport.primary_required'='请先设置有效的主要城镇再使用高级模式。';
    'townymapaddon.teleport.settings.title'='传送路线查看器设置'; 'townymapaddon.teleport.primary_town'='主要城镇'; 'townymapaddon.teleport.save_primary'='验证并保存主要城镇'; 'townymapaddon.teleport.saved'='传送设置已保存。'; 'townymapaddon.teleport.invalid_town'='当前 EarthMC 城镇数据中没有该城镇。'; 'townymapaddon.teleport.settings.advanced_enabled'='启用高级传送模式'; 'townymapaddon.teleport.settings.command_action'='命令按钮操作'; 'townymapaddon.teleport.command_mode.clipboard'='复制命令到剪贴板'; 'townymapaddon.teleport.command_mode.chat'='将命令填入聊天框'; 'townymapaddon.teleport.command_mode.execute'='立即执行命令'; 'townymapaddon.teleport.settings.town_spawns'='显示城镇传送点'; 'townymapaddon.teleport.settings.nation_spawns'='显示国家传送点'; 'townymapaddon.teleport.settings.uncertain'='显示不确定路线'; 'townymapaddon.teleport.settings.route_line'='显示路线'; 'townymapaddon.teleport.settings.auto_fit'='自动缩放到所选路线'; 'townymapaddon.teleport.settings.target_marker'='显示目的地标记'; 'townymapaddon.teleport.settings.arrival_marker'='显示抵达标记'; 'townymapaddon.teleport.settings.hint'='双击 Xaero 世界地图上的坐标即可打开浮动查看器。';
    'townymapaddon.teleport.advanced.locked'='成员身份安全锁：确认后才能复制高级命令。'; 'townymapaddon.teleport.advanced.clipboard_only'='高级命令只能复制到剪贴板。'; 'townymapaddon.teleport.advanced.confirm'='我了解成员身份风险'; 'townymapaddon.teleport.command_result.copied'='命令已复制。'; 'townymapaddon.teleport.command_result.chat_ready'='命令已填入聊天框，按回车发送。'; 'townymapaddon.teleport.command_result.executed'='命令已执行。'; 'townymapaddon.teleport.command_result.cooldown'='命令之间请等待一秒。'; 'townymapaddon.teleport.command_result.unavailable'='该命令当前不可用。'
  };
  'zh_tw' = @{
    'townymapaddon.hunter.activity.title'='獵人動態'; 'townymapaddon.hunter.chat.warning_prefix'='[獵人警報] [警告]'; 'townymapaddon.hunter.chat.notification_prefix'='[獵人警報]'; 'townymapaddon.hunter.hud.possible_hunter'='疑似獵人'; 'townymapaddon.hunter.hud.warning'='警告'; 'townymapaddon.hunter.hud.recent_event'='最近事件'; 'townymapaddon.hunter.candidate.outlaw_count'='被 %1$s 個城鎮通緝'; 'townymapaddon.hunter.hud.tracked'='%1$s · %2$s格 %3$s'; 'townymapaddon.hunter.hud.visible_claim'='可見 · %1$s'; 'townymapaddon.hunter.hud.lost_claim'='失聯 %1$s · %2$s'; 'townymapaddon.hunter.hud.risk_score'='風險 %1$s %2$s'; 'townymapaddon.hunter.hud.tp_threat'='傳送威脅 ~%1$s格 · %2$s'; 'townymapaddon.hunter.hud.more'='另有 %1$s 人';
    'townymapaddon.teleport.title'='傳送路線檢視器'; 'townymapaddon.teleport.find_here'='尋找前往此處的傳送點'; 'townymapaddon.teleport.mode.standard'='標準'; 'townymapaddon.teleport.mode.advanced'='進階'; 'townymapaddon.teleport.target'='目標'; 'townymapaddon.teleport.target_context'='目標：%1$s'; 'townymapaddon.teleport.target_waypoint'='目標航點'; 'townymapaddon.teleport.arrival_waypoint'='抵達航點'; 'townymapaddon.teleport.waypoint_created'='已建立航點'; 'townymapaddon.teleport.blocks'='%1$s 格'; 'townymapaddon.teleport.loading'='正在載入傳送路線…'; 'townymapaddon.teleport.none'='找不到可用的傳送路線。'; 'townymapaddon.teleport.wilderness'='荒野'; 'townymapaddon.teleport.clear_results'='清除結果'; 'townymapaddon.teleport.results_cleared'='結果及地圖路線已清除。雙擊新地點再次搜尋。'; 'townymapaddon.teleport.destination_coords'='目的地：X %1$s，Z %2$s'; 'townymapaddon.teleport.primary_required'='請先設定有效的主要城鎮再使用進階模式。';
    'townymapaddon.teleport.settings.title'='傳送路線檢視器設定'; 'townymapaddon.teleport.primary_town'='主要城鎮'; 'townymapaddon.teleport.save_primary'='驗證並儲存主要城鎮'; 'townymapaddon.teleport.saved'='傳送設定已儲存。'; 'townymapaddon.teleport.invalid_town'='目前 EarthMC 城鎮資料中沒有該城鎮。'; 'townymapaddon.teleport.settings.advanced_enabled'='啟用進階傳送模式'; 'townymapaddon.teleport.settings.command_action'='指令按鈕動作'; 'townymapaddon.teleport.command_mode.clipboard'='複製指令到剪貼簿'; 'townymapaddon.teleport.command_mode.chat'='將指令填入聊天欄'; 'townymapaddon.teleport.command_mode.execute'='立即執行指令'; 'townymapaddon.teleport.settings.town_spawns'='顯示城鎮傳送點'; 'townymapaddon.teleport.settings.nation_spawns'='顯示國家傳送點'; 'townymapaddon.teleport.settings.uncertain'='顯示不確定路線'; 'townymapaddon.teleport.settings.route_line'='顯示路線'; 'townymapaddon.teleport.settings.auto_fit'='自動縮放至所選路線'; 'townymapaddon.teleport.settings.target_marker'='顯示目的地標記'; 'townymapaddon.teleport.settings.arrival_marker'='顯示抵達標記'; 'townymapaddon.teleport.settings.hint'='雙擊 Xaero 世界地圖上的座標即可開啟浮動檢視器。';
    'townymapaddon.teleport.advanced.locked'='成員身分安全鎖：確認後才能複製進階指令。'; 'townymapaddon.teleport.advanced.clipboard_only'='進階指令只能複製到剪貼簿。'; 'townymapaddon.teleport.advanced.confirm'='我瞭解成員身分風險'; 'townymapaddon.teleport.command_result.copied'='指令已複製。'; 'townymapaddon.teleport.command_result.chat_ready'='指令已填入聊天欄，按 Enter 傳送。'; 'townymapaddon.teleport.command_result.executed'='指令已執行。'; 'townymapaddon.teleport.command_result.cooldown'='指令之間請等待一秒。'; 'townymapaddon.teleport.command_result.unavailable'='該指令目前無法使用。'
  };
  'ja_jp' = @{
    'townymapaddon.hunter.activity.title'='ハンター活動'; 'townymapaddon.hunter.chat.warning_prefix'='[ハンター警報] [警告]'; 'townymapaddon.hunter.chat.notification_prefix'='[ハンター警報]'; 'townymapaddon.hunter.hud.possible_hunter'='ハンター候補'; 'townymapaddon.hunter.hud.warning'='警告'; 'townymapaddon.hunter.hud.recent_event'='最近のイベント'; 'townymapaddon.hunter.candidate.outlaw_count'='%1$s 個の町で無法者'; 'townymapaddon.hunter.hud.tracked'='%1$s · %2$sm %3$s'; 'townymapaddon.hunter.hud.visible_claim'='可視 · %1$s'; 'townymapaddon.hunter.hud.lost_claim'='見失い %1$s · %2$s'; 'townymapaddon.hunter.hud.risk_score'='危険度 %1$s %2$s'; 'townymapaddon.hunter.hud.tp_threat'='TP脅威 ~%1$sm · %2$s'; 'townymapaddon.hunter.hud.more'='ほか %1$s 人';
    'townymapaddon.teleport.title'='テレポート経路'; 'townymapaddon.teleport.find_here'='ここへのテレポートを検索'; 'townymapaddon.teleport.mode.standard'='標準'; 'townymapaddon.teleport.mode.advanced'='上級'; 'townymapaddon.teleport.target'='目的地'; 'townymapaddon.teleport.target_context'='目的地：%1$s'; 'townymapaddon.teleport.target_waypoint'='目的地ウェイポイント'; 'townymapaddon.teleport.arrival_waypoint'='到着ウェイポイント'; 'townymapaddon.teleport.waypoint_created'='ウェイポイントを作成しました'; 'townymapaddon.teleport.blocks'='%1$s ブロック'; 'townymapaddon.teleport.loading'='テレポート経路を読み込み中…'; 'townymapaddon.teleport.none'='利用可能なテレポート経路がありません。'; 'townymapaddon.teleport.wilderness'='荒野'; 'townymapaddon.teleport.clear_results'='結果を消去'; 'townymapaddon.teleport.results_cleared'='結果と地図上の経路を消去しました。別の地点をダブルクリックしてください。'; 'townymapaddon.teleport.destination_coords'='目的地：X %1$s、Z %2$s'; 'townymapaddon.teleport.primary_required'='上級モードを使うには有効な本拠地を設定してください。';
    'townymapaddon.teleport.settings.title'='テレポート経路設定'; 'townymapaddon.teleport.primary_town'='本拠地'; 'townymapaddon.teleport.save_primary'='本拠地を確認して保存'; 'townymapaddon.teleport.saved'='テレポート設定を保存しました。'; 'townymapaddon.teleport.invalid_town'='現在の EarthMC 町データに存在しません。'; 'townymapaddon.teleport.settings.advanced_enabled'='上級テレポートモードを有効化'; 'townymapaddon.teleport.settings.command_action'='コマンドボタンの動作'; 'townymapaddon.teleport.command_mode.clipboard'='クリップボードにコピー'; 'townymapaddon.teleport.command_mode.chat'='チャット欄に入力'; 'townymapaddon.teleport.command_mode.execute'='すぐに実行'; 'townymapaddon.teleport.settings.town_spawns'='町スポーンを表示'; 'townymapaddon.teleport.settings.nation_spawns'='国家スポーンを表示'; 'townymapaddon.teleport.settings.uncertain'='不確実な経路を表示'; 'townymapaddon.teleport.settings.route_line'='経路線を表示'; 'townymapaddon.teleport.settings.auto_fit'='選択経路に自動調整'; 'townymapaddon.teleport.settings.target_marker'='目的地マーカーを表示'; 'townymapaddon.teleport.settings.arrival_marker'='到着マーカーを表示'; 'townymapaddon.teleport.settings.hint'='Xaero 世界地図上の座標をダブルクリックすると開きます。';
    'townymapaddon.teleport.advanced.locked'='所属変更の安全ロック：確認後に上級コマンドをコピーできます。'; 'townymapaddon.teleport.advanced.clipboard_only'='上級コマンドはコピーのみ可能です。'; 'townymapaddon.teleport.advanced.confirm'='所属変更の危険性を理解しました'; 'townymapaddon.teleport.command_result.copied'='コマンドをコピーしました。'; 'townymapaddon.teleport.command_result.chat_ready'='チャット欄に入力しました。Enter で送信します。'; 'townymapaddon.teleport.command_result.executed'='コマンドを実行しました。'; 'townymapaddon.teleport.command_result.cooldown'='コマンドの間隔を1秒空けてください。'; 'townymapaddon.teleport.command_result.unavailable'='このコマンドは現在利用できません。'
  }
}
foreach ($locale in $maps.Keys) {
  $path = Join-Path $root "$locale.json"
  $obj = Get-Content -Raw -Encoding UTF8 $path | ConvertFrom-Json
  foreach ($entry in $maps[$locale].GetEnumerator()) {
    if ($null -eq $obj.PSObject.Properties[$entry.Key]) { $obj | Add-Member -NotePropertyName $entry.Key -NotePropertyValue $entry.Value }
    else { $obj.($entry.Key) = $entry.Value }
  }
  [IO.File]::WriteAllText($path, ($obj | ConvertTo-Json -Depth 20), [Text.UTF8Encoding]::new($false))
}
