name: Sync GitHub Issues and Comments to Discord Forum

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  sync-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Discord Forum Channel
        uses: Marvinsv/github-disicord-threads@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
